### ISSUE TITLE
Display README + Usage Restriction info on the collection page

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#100]
I bet it's possible to configure the app to spit out the README info on a collection page. For example, here's a current view to which I would think could be added a display of the README data:
```
---
identifier: mixed.gwas.Zhao_Teng_2017

taxid: 3847

scientific_name: Glycine max

scientific_name_abbrev: glyma

genotype:
  - 200 diverse soybean accessions

citation: "Zhao, X. et al. Loci and candidate genes conferring resistance to soybean cyst nematode HG type 2.5.7. BMC Genomics 18, 462 (2017)"

synopsis: "The aim of the present study was to investigate the genome-wide genetic architecture of resistance to SCN HG Type 2.5.7 (race 1) in landrace and elite cultivated soybeans."

description: "A total of 200 diverse soybean accessions were screened for resistance to SCN HG Type 2.5.7 and genotyped through sequencing using the Specific Locus Amplified Fragment Sequencing (SLAF-seq) approach with a 6.14-fold average sequencing depth. A total of 33,194 SNPs were identified with minor allele frequencies (MAF) over 4%, covering 97% of all the genotypes. Genome-wide association mapping (GWAS) revealed thirteen SNPs associated with resistance to SCN HG Type 2.5.7. These SNPs were distributed on five chromosomes (Chr), including Chr7, 8, 14, 15 and 18. Four SNPs were novel resistance loci and nine SNPs were located near known QTL. A total of 30 genes were identified as candidate genes underlying SCN resistance. Conclusions: A total of sixteen novel soybean accessions were identified with significant resistance to HG Type 2.5.7. The beneficial alleles and candidate genes identified by GWAS might be valuable for improving marker-assisted breeding efficiency and exploring the molecular mechanisms underlying SCN resistance."

genotyping_platform: Zhao_Teng_2017

genotyping_method: "SLAF-seq: Specific Locus Amplified Fragment Sequencing"

publication_title: "Loci and candidate genes conferring resistance to soybean cyst nematode HG type 2.5.7"

publication_doi: 10.1186/s12864-017-3843-y

contributors: "Xue Zhao, Weili Teng, Yinghui Li, Dongyuan Liu, Guanglu Cao, Dongmei Li, Lijuan Qiu, Hongkun Zheng, Yingpeng Han, Wenbin Li"
```
![Screenshot 2022-05-06 at 06-42-46 mixed gwas Zhao_Teng_2017 - data legumeinfo org Glycine max genetic mixed gwas Zhao_Teng_](https://user-images.githubusercontent.com/5657219/167133945-01a4dec0-82f7-44f8-b1e9-810e95608483.png)

**Comment by sammyjava** [comment]
Another, parallel, option would be to have a click-n-show on legumeinfo.org on the Collections page, with a down arrow to open a README view under the collection line, up arrow to close it, still click on the collection name to go to the Datastore collection. That would involve throwing some Javascript on the page to do so, but doing an HTTP request over to the Datastore to suck the full README, which should be pretty quick for most users if the LIS site is decently peered (I've never looked into how quickly requests get returned from legumeinfo.org but I presume it's not bad. If that's too slow, we can load the READMEs into the website under _data and use GitHub to serve them, which has pretty good peering and bandwidth. I download the READMEs now, anyway, to build the _data files locally, but I delete them when I'm done.)

**Comment by adf-ncgr** [comment]
I'm not sure I fully follow your descriptions but agree that it would be nice to display README info in an easily Accessible fashion. It might also be nice to make linkages to publications from which the collections were derived more prominent.

**Comment by sammyjava** [comment]
Although I hijacked my own thread by mentioning legumeinfo.org, this issue is about data.legumeinfo.org. Looking for a "hijack" icon for my post above.... Just saying that when you view a data.legumeinfo.org collection you see the README data underneath the file list just as we currently see "Abbreviations" etc.

**Comment by sammyjava** [comment]
We'll say the "confused" emoji is appropriate for tagging hijacks. :)

**Comment by nathanweeks** [comment]
> I bet it's possible to configure the app to spit out the README info on a collection page. For example, here's a current view to which I would think could be added a display of the README data:

That should be doable. I assume you would want the README embedded at the bottom, below the "Please contact us..." line?

**Comment by sammyjava** [comment]
I'll defer to @cann0010 or you for the placement decision.

**Comment by cann0010** [comment]
Placement for the README text ... I am not sure. It may be best to see whether it looks better directly under the file listing ... or below the "contact us" line. For the collections with more files (e.g. annotations), it may not be apparent that there is more content off-screen.

If possible, I think I would prefer un-rendered, plain text, rather than the non-selectable (though pretty) rendered text that comprises the footer. That's been a frustration with h5ai.

**Comment by nathanweeks** [comment]
> If possible, I think I would prefer un-rendered, plain text, rather than the non-selectable (though pretty) rendered text that comprises the footer. That's been a frustration with h5ai.

Probably worth a separate issue to track, but I located & excised a single line of JavaScript in the h5ai source to make the text selectable (see the relevant repo). Hopefully this doesn't break anything, but if it does, please let me know.

**Comment by cann0010** [comment]
@nathanweeks - Where are the h5ai changes viewable?

**Comment by nathanweeks** [comment]
https://github.com/legumeinfo/h5ai/tree/data.legumeinfo.org

**Comment by cann0010** [comment]
@nathanweeks - Looks good to me (making the rendered text selectable). That removes a long-time irritation for me!
For the benefit of others here: I had to clear my cache before seeing the change. What has changed: text in the "Overview of data" and the "Abbreviations" block is now selectable, at e.g. https://data.legumeinfo.org/Cicer/arietinum/genomes/ 
Leaving the issue open regarding the "Display README" enhancement.

**Comment by nathanweeks** [comment]
@cann0010 : Attempt #1 at appending the README.*.yml at the end of the footer: https://data.legumeinfo.org/Cicer/arietinum/genomes/CDCFrontier.gnm1.GkHc/

**Comment by cann0010** [comment]
I am thinking that "above the fold" (above the footer with "Abbreviations") might be better, if not too difficult to implement.

Another improvement would be two wrap the text to screen width. That makes me wonder: could the rendering machinery that handles wrapping in the header and footer be employed to display the README text?

**Comment by nathanweeks** [comment]
> I am thinking that "above the fold" (above the footer with "Abbreviations") might be better, if not too difficult to implement.
> 
> Another improvement would be two wrap the text to screen width. That makes me wonder: could the rendering machinery that handles wrapping in the header and footer be employed to display the README text?

Difficult & taxing for my meager front-end skills, perhaps, but doable :-)  And both done.

**Comment by cann0010** [comment]
I love it! Excellent idea @sammyjava to display the README in the collection view, and excellent job figuring out how to make it happen, @nathanweeks. With satisfaction, I'll close the issue.

**Comment by adf-ncgr** [comment]
I agree it's nice, but wondering if it is interfering with display of usage restriction info in the footers? I thought the way we were effecting that was via _h5ai.footers.html files, but am no longer seeing the contents of that file displayed for 
https://data.legumeinfo.org/Medicago/sativa/genomes/RegenSY27x.gnm0_9.2VSM/
(as a recent example of a pre-publication genome)

it could be that I'm getting confused, but will reopen this issue until we get it sorted out. It's certainly fine with me if we want to use an alternative mechanism for alerting people to usage-restricted datasets...

**Comment by cann0010** [comment]
Hmm. I hadn't checked such cases with a usage agreement. There might be a technical solution for displaying that in the footer; however, we could also effect the usage agreement within the README, via the license field. Something like the following (which is, admittedly, a lot of text to put into the value for the "license" field). OR, add a new usage field to handle this kind of case. Not sure what I think of this; just suggesting it as a possible data hack.

```
license: "Open, with usage agreement: As a public service, the researchers who have assembled the genome of Medicago sativa RegenSY27x are making the genome assembly available before scientific publication according to the Ft. Lauderdale Accord (https://www.genome.gov/Pages/Research/WellcomeReport0303.pdf). These data sets have been made available from the Legume Federation / LIS Data Store prior to peer-reviewed publication of the data, with the expectation and desire to publish analysis of the data in a reasonable time without preemption by other groups. By accessing these data, you agree not to publish any articles containing analyses of genes or genomic data on a whole genome or chromosome scale prior to publication by the sequencing consortium of a comprehensive genome analysis ("Reserved Analyses") except with permission of the sequencing consortium. Reserved analyses include the identification of complete (whole genome) sets of genomic features such as genes, gene families, regulatory elements, repeat structures, GC content, or any other genome feature, and whole-genome- or chromosome- scale comparisons with other species. For specific questions about data use please send your inquiry to Dr. Deborah Samac, debby.samac@usda.gov Also note that this assembly data is being made available prior to deposition at GenBank. The assemblies MAY CHANGE during deposition. Therefore, please treat these assemblies as initial drafts versions. If you will be employing the data for non-reserved analyses, such as cloning a gene of interest, designing mapping panels or to analyze a gene family etc., please reference "USDA Alfalfa Genome Sequencing, pre-publication" and this URL in your provisional citation. These data may be freely downloaded and used by all who respect the restrictions in the previous paragraphs. The assembly and annotations should not be redistributed or repackaged without permission. Once the sequence is moved to unreserved status, the data will be freely available for any subsequent use. If you wish to use this data, please contact Dr. Deborah Samac, debby.samac@usda.gov with your plans, to ensure that proposed usage of sequence data are not Reserved Analyses. Principal Investigators: Dr. Deborah Samac, debby.samac@usda.gov"
```

**Comment by adf-ncgr** [comment]
If we think it will be sufficiently visible to alert people, we could just have the full usage policy in a separate file (there is one already, copying the model of those who went before me) and reference that file from the README. But, I think it should be at the top of the README if we take either of these approaches.

**Comment by nathanweeks** [comment]
> I agree it's nice, but wondering if it is interfering with display of usage restriction info in the footers? I thought the way we were effecting that was via _h5ai.footers.html files, but am no longer seeing the contents of that file displayed for
https://data.legumeinfo.org/Medicago/sativa/genomes/RegenSY27x.gnm0_9.2VSM/
(as a recent example of a pre-publication genome)

I didn't realize that there were custom _h5ai.footer.html files sprinkled in the data store, and had [hard-coded the wording from the main html footer in the h5ai code](https://github.com/legumeinfo/h5ai/blob/9bfd62f055962178fb56a97268eac3518609f334/src/_h5ai/private/php/ext/class-custom.php#L33-L58), as it was easier to implement that way when that wording came before the README text (and allowed local testing via the Docker [compose file](https://github.com/legumeinfo/h5ai/blob/data.legumeinfo.org/compose.yml) and datastore-metadata git submodule). I agree that the license wording should be part of the metadata somehow (whether in a separate LICENSE file, or in the README).

**Comment by cann0010** [comment]
I see that we're handling usage restriction now in kind of a two-pronged way: with text in _h5ai.footers.html within a collection, and with a corresponding plain-text file called "usage_policy.txt". There are currently eight such cases (with _h5ai.footers.html and usage_policy.txt).

This is a bit cumbersome, I think. The use of _h5ai.footers.html to display the restriction message has the advantage of being generic, but the disadvantage of requiring someone to generate the file and duplicate information from the usage_policy.txt ... and then remember to remove both files when the restriction is lifted.

I think it would be preferable (if the coding is reasonable) to display the contents of  usage_policy.txt if that file is present, then the contents of the README.

**Comment by sammyjava** [comment]
Since the README is a YAML, I'd think that a field like:
```
license: restricted
```
could trigger some sort of usage restriction alert, perhaps which sucks a text file from elsewhere. Certainly can do that in the python script that loads into the website.

But bottom line: the implementation of "usage restriction" needs to be put in the Datastore spec (README and perhaps another file with the specific usage restrictions).  I didn't know we hosted restricted data on the public Datastore or I would have tried to come up with something.

SO, not surprisingly, that is a separate topic: specification of Datastore usage restrictions implementation. Which I just added to the  datastore-specifications repo: legumeinfo/datastore-specifications#25

**Comment by sammyjava** [comment]
I have changed the title of this issue to indicate that it has morphed into the display of usage restriction info as well as the README. We need the usage restriction spec legumeinfo/datastore-specifications/issues/25  before this issue can be further addressed.

**Comment by sammyjava** [comment]
> thanks all- seems like this is moving in the right direction. I have no vested interest in using the h5ai machinery for this, was just following precedent. It does seem to make more sense to decouple it firmly from the specific mechanisms used for display.
> 
> I should probably note that much of the data we bring in from Phytozome is under similar usage restriction. See species browser at https://phytozome-next.jgi.doe.gov/ and look for RST vs UNRST icons. I suppose that we ought to be copying into place the usage agreements when we grab such datasets- I think sometimes we do, sometimes we indicate that there is a usage agreement in the license but don't specify explicitly what it is. Whenever we get the new approach to this settled, I can try to clean this up.

Copied this over to legumeinfo/datastore-specifications/issues/25

**Comment by sammyjava** [comment]
I think we're good with Nathan's solution.
