### ISSUE TITLE
vigra.VC1973A.gnm6.mrk.microsatellites.gff3 has incorrect ID values

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#101]
As per the new-ish spec, ID must be full-yuck. Therefore a line like
```
vigra.VC1973A.gnm6.Vr01 MISA    genetic_marker  3043    3054    .       +       .       Name=VrDGRC1p4SSR9905;ID=1;Note=(AAAG)3
```
must be transformed to:
```
vigra.VC1973A.gnm6.Vr01 MISA    genetic_marker  3043    3054    .       +       .       Name=VrDGRC1p4SSR9905;ID=vigra.VC1973A.gnm6.VrDGRC1p4SSR9905;Note=(AAAG)3
```

**Comment by sammyjava** [comment]
@cann0010 bounce it to me if you're busy, but I'm now on a crusade to have folks fully experience the current spec. :)

**Comment by cann0010** [comment]
I appreciate the crusade, but I'll need to bounce it back. I'm up against a batch of large administrative deadlines that will keep me swamped through early June. Five-year plan, annual report, agreement renewals, budgets, student on-boarding, etc.

**Comment by sammyjava** [comment]
No prob, mission accomplished just by having you bounce it back to me. :)

**Comment by sammyjava** [comment]
Also, since those Note attributes are actually motifs, for consistency with other (soy) files I think I'll change it to Motif:
```
vigra.VC1973A.gnm6.Vr01 MISA genetic_marker 3043 3054 . + . Name=VrDGRC1p4SSR9905;ID=vigra.VC1973A.gnm6.VrDGRC1p4SSR9905;Motif=(AAAG)3
```
which I don't think will break anything. Normally Note is used for things like functional descriptions.

**Comment by sammyjava** [comment]
(Hrm. BioJava's Feature.getAttribute() is case-sensitive. I could swear I saw somewhere that GFF readers shouldn't care. I'll be that way, but I'm a bit surprised I have to do work to make it so.)

**Comment by adf-ncgr** [comment]
gff attributes are case sensitive; from spec:
Note that attribute names are case sensitive. "Parent" is not the same as "parent".

**Comment by sammyjava** [comment]
Ahhh, thanks for tracking that down. Explains why BioJava is case-sensitive. I've now implemented case-insensitivity in the GFF loaders given what we're dealing with, which is terribly (case) insensitive data curators.

**Comment by sammyjava** [comment]
Done.
