### ISSUE TITLE
Gyeongwon.gnm3.ann1 multiple parents in GFF

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#102]
Caused by: java.lang.RuntimeException:
Parent vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.1,vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.2 not loaded before child vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.1:exon:16254. Is the GFF sorted?

Did we decide something on Gyeongwon, like skip it? I don't remember.

**Comment by cann0010** [comment]
I don't recall anything unusual about that genotype. You might be thinking of Xiabao_II, which we did decide to skip.

**Comment by adf-ncgr** [comment]
we had run into multi-parents recently in #99 where I said we could skip loading since we have a newer version of R108. But, it looks like we ought to actually have a fix for this general issue (allowed by gff3 but often problematic in practice). I'll try to script something up.

**Comment by sammyjava** [comment]
So it turns out I misinterpreted the Exception, and it is actually in my code, not BioJava. Since a parent with a comma inside isn't already seen, my code thought there was a sorting issue. The data model supports multiple parents (the feature being processed is just stored as a child) so I've updated the code to handle the multi-parent case (as long as a comma is the delimiter).

I did leave the exception in if the GFF isn't sorted -- I don't actually require sorting (since I'm using maps with keys) but I believe that some other processes require sorted GFFs so I've had that in there as a canary in a coal mine. But if you think we should offer unsorted GFFs in the Datastore, I can update my loader to not throw that exception.

**Comment by adf-ncgr** [comment]
OK, I think it is a good idea to require that parents precede children; there are occasional conflicts between this requirement and the location-based sorting that tabix indexing requires, but my feeling is that these indicate problems with the data and should be corrected. Allowing multiple parents is certainly easier, although we may decide we still want to transform such files since they may cause issues for some downstream processes. But I'm happy to defer that until we face such an issue. Shall we close this?

**Comment by sammyjava** [comment]
Yup, closing, I've loaded this GFF into dev CowpeaMine with multiple parents:
```
cowpeamine-dev=> SELECT * FROM sequencefeature WHERE id IN (SELECT sequencefeature FROM childfeaturessequencefeature WHERE childfeatures=(SELECT id FROM sequencefeature WHERE primaryidentifier ='vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.1:exon:16254'));
-[ RECORD 1 ]----------+--------------------------------------------
score                  | 
scoretype              | 
description            | 
id                     | 79466561
symbol                 | 
length                 | 2608
name                   | Vang0010ss00020.1
assemblyversion        | gnm3
annotationversion      | ann1
secondaryidentifier    | Vang0010ss00020.1
primaryidentifier      | vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.1
sequenceontologytermid | 2466409
supercontiglocationid  | 79663632
organismid             | 3000002
chromosomelocationid   | 
supercontigid          | 79000193
sequenceid             | 79663633
chromosomeid           | 
strainid               | 3000003
class                  | org.intermine.model.bio.MRNA
-[ RECORD 2 ]----------+--------------------------------------------
score                  | 
scoretype              | 
description            | 
id                     | 79466656
symbol                 | 
length                 | 1938
name                   | Vang0010ss00020.2
assemblyversion        | gnm3
annotationversion      | ann1
secondaryidentifier    | Vang0010ss00020.2
primaryidentifier      | vigan.Gyeongwon.gnm3.ann1.Vang0010ss00020.2
sequenceontologytermid | 2466409
supercontiglocationid  | 79663674
organismid             | 3000002
chromosomelocationid   | 
supercontigid          | 79000193
sequenceid             | 79663675
chromosomeid           | 
strainid               | 3000003
class                  | org.intermine.model.bio.MRNA
```
