### ISSUE TITLE
de-tRNA the A17_HM341 mRNA FASTA

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#103]
Calling this a DS issue now since it sounds like we'll have a policy of the mrna.fasta file only containing actual coding mRNAs that are represented as mRNA types in the GFF (if they're in there).

On 5/25/22 9:10 AM, Sam Hokin wrote:
> The FASTA has mRNA records (of course) while the same transcript is listed as a tRNA in the GFF. This causes a conflict during loading, since both extend Transcript (tRNA -> ncRNA -> Transcript), so I'm trying to load two different objects with the same Transcript primary identifier. Such is hierarchy.
>
> Shall I just load tRNA records as mRNA in general? (Even though we do support tRNA in the data model, which extends ncRNA which extends Transcript). Or call the tRNAs in this GFF mRNA and presume that we may have standalone tRNAs in GFFs in other cases that are not also listed as mRNAs in the FASTA?
>
We should probably just partition the fasta file so that the one called mRNA actually contains only mRNA. I think gffread transcript generation only cares about exons, so puts them all in (whereas CDS obviously only apply to mRNA). I'll try to get this done today.

adf

**Comment by adf-ncgr** [comment]
OK, the tRNAs are now in their own medtr.A17_HM341.gnm4.ann2.G3ZY.trna.fna.gz file and medtr.A17_HM341.gnm4.ann2.G3ZY.mrna.fna.gz contains only things corresponding to mRNA records in the gff. Note that some of these are actually children of transposable_element_genes and don't have CDS, resulting in #mRNA>#protein but I don't think that will cause any problems so I've left it as a quirk of this annotation.
