### ISSUE TITLE
arahy.Shitouqi or arahy.Shitoqi? Inconsistent naming, pick one.

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#106]
The collection is `Shitouqi.gnm1.L4VP` while the chromosomes are named `arahy.Shitoqi.gnm1.chr01` etc. That's not allowed, yuck identifiers must match the collection name.

Since https://www.ncbi.nlm.nih.gov/data-hub/genome/GCA_003713155.1/ says "Shitouqi" I vote for adding the "u" to the identifiers in the FASTA and elsewhere.

Your choice, though, @cann0010 .

**Comment by sammyjava** [comment]
Never mind, just found this Changes line:
```
2021-06-17: changed accession name from Shitoqi to Shitouqi throughout.
```
So I'll make sure it's Shitouqi throughout.

**Comment by sammyjava** [comment]
Note: this genome collection has a file `arahy.Shitouqi.gnm1.L4VP.contigs.fna.gz` which I ignore. Normally contigs are included in the genome_main FASTA and that's all I load into mines.

**Comment by cann0010** [comment]
Agreed: "Shitouqi" is correct. I have made that change in the pseudomolecule names in genome_main.fna. Mentioning @sdash-github and @weihuang12 in case this change affects other peanut resources (browsers etc.).

**Comment by sammyjava** [comment]
Yeah turned out I had an old version of the file, I should be sure to freshen my local files before loading.
