### ISSUE TITLE
chafa.MN87 or chafa.NM87?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#107]
```
[shokin@shokin-mines genomes]$ zgrep ">" MN87.gnm1.JXFN/chafa.MN87.gnm1.JXFN.genome_main.fna.gz | head
>chafa.NM87.gnm1.scaffold56111_cov316 QANZ01000001.1
>chafa.NM87.gnm1.scaffold94823_cov238 QANZ01000002.1
>chafa.NM87.gnm1.scaffold93662_cov218 QANZ01000003.1
>chafa.NM87.gnm1.scaffold7732_cov132 QANZ01000004.1
>chafa.NM87.gnm1.scaffold11692_cov268 QANZ01000005.1
>chafa.NM87.gnm1.scaffold49528_cov240 QANZ01000006.1
>chafa.NM87.gnm1.scaffold34203_cov132 QANZ01000007.1
>chafa.NM87.gnm1.scaffold24366_cov82 QANZ01000008.1
>chafa.NM87.gnm1.scaffold31949_cov184 QANZ01000009.1
>chafa.NM87.gnm1.scaffold40518_cov150 QANZ01000010.1
```

**Comment by sammyjava** [comment]
Could really use that QC tool one of these days. Other than the one named "Sam."

**Comment by adf-ncgr** [comment]
pretty sure chafa is more likely to derive from MN than NM, but I'm a little unclear as to where the designation came from since NCBI has "NF-2018-5"; FWIW the README indicates it as:
genotype:
  - MN87 (ICERNS isolate NF-2018-5)
but I'm punting it to @cann0010 who I think is nominated by the README:
data_curators: Steven Cannon

**Comment by cann0010** [comment]
Good catch. The genotype was collected by Susan Singer in Minnesota in 1987. I have fixed the assembly, updated the README and re-committed/pushed.
It looks like the native range does extend to NM though: https://butterflies.naba.org/butterfly-gardening-partridge-pea-chamaecrista-fasciculata/
Incidentally, we now have a really good genome assembly for Chamaecrista, from an accession from my garden (the genotype is registered at the Iowa State Herbarium). We'll make it public once we have an annotation for it and are closer to publication.

**Comment by adf-ncgr** [comment]
thanks Steven- I'll be on the watch for partridge peas, apparently misnamed:

>  Supposedly, European explorers called this wildflower partridge because they mistook the quail that they saw eating its seeds to be partridges.

we have plenty of quail here...
