### ISSUE TITLE
CIAT22838.gnm1.ann1 has non-yuck IDs

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#108]
For example, from the CDS fasta:
```
>Ae01g14820.1 Ae01g14820   Ae01:17540075-17550489(-)
```
Fortunately this throws an exception in the lis-annotation loader so I don't get crap in LegumeMine.

(I wonder if I should write a standalone DS QC tool because I just don't see it happening otherwise.)

**Comment by adf-ncgr** [comment]
OK, should be fixed- sorry about the inconvenience
