### ISSUE TITLE
Annotation collections that fail loading at this point in LegumeMine loading

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#109]
These all fail loading for various reasons.

- [x] CIAT22838.gnm1.ann1 - bad IDs
- [x] Daliak.gnm2.ann1 - files missing, that may be on me
- [x] Cameor.gnm1.ann1 - files missing, that may be on me
- [x] XinJiang - ObjectStore error, coulda been a glitch
- [x] Amiga - GFF missing some IDs
- [ ] MG20 - bad identifiers
- [x] Zh13 - location conflict, I'll have to sort that one out

Annotations are still loading so there may be more.

**Comment by sammyjava** [comment]
CIAT: @adf-ncgr 
```
Caused by: java.lang.RuntimeException: Could not get secondaryIdentifier for feature:Ae0000020.1 in file:aesev.CIAT22838.gnm1.ann1.ZM3R.iprscan.gff3.gz
```
Now that I'm loading iprscan we've got another class of failure.

**Comment by adf-ncgr** [comment]
There must be 50 ways to break your loaders. But I added the full yuck, Chuck. Let me know if there was more to do on CIAT22838.gnm1.ann1 or else go ahead and mark that one as resolved.

**Comment by sammyjava** [comment]
@adf-ncgr Amiga:
```
Caused by: java.lang.RuntimeException: GFF line does not include ID: lupal.Amiga.gnm1.Lalb_chloroplast_genome   Geneious        region  0       151915  0.0     0       Is_circular=true
        at org.intermine.bio.dataconversion.AnnotationFileConverter.processGFF3File(AnnotationFileConverter.java:443)
```

**Comment by sammyjava** [comment]
@adf-ncgr Wm82.gnm2.ann2:
```
Caused by: java.lang.RuntimeException: ID gene0 does not match collection Wm82.gnm2.ann2.BG1Q
        at org.intermine.bio.dataconversion.AnnotationFileConverter.processGFF3File(AnnotationFileConverter.java:446)
```

**Comment by sammyjava** [comment]
Whoo hooo! First use of my very nascent annotation collection validator:
```
[shokin@shokin-mines datastore]$ scripts/validate-annotation-collection /data/v2/Lupinus/albus/annotations/Amiga.gnm1.ann1.3GKS
## Validating annotation collection Amiga.gnm1.ann1.3GKS with gensp=lupal
## Required file types:
##    gene_models_main.gff3.gz
##    protein.faa.gz
##    cds.fna.gz
##    mrna.fna.gz
## Optional file types:
##    legfed_v1_0.M65K.gfa.tsv.gz
##    legfed_v1_0.M65K.pathway.tsv.gz
10:30:05 [main] INFO  org.biojava.nbio.genome.parsers.gff.GFF3Reader - Reading: /tmp/gene_models_main.gff3
## INVALID: GFF line does not include ID:
## INVALID: lupal.Amiga.gnm1.Lalb_chloroplast_genome    Geneious        region  0       151915  0.0     0       Is_circular=true
```

**Comment by sammyjava** [comment]
And...
```
## Validating annotation collection MG20.gnm3.ann1.WF9B with gensp=lotja
## Required file types:
##    gene_models_main.gff3.gz
##    protein.faa.gz
##    cds.fna.gz
##    mrna.fna.gz
## Optional file types:
##    legfed_v1_0.M65K.gfa.tsv.gz
##    legfed_v1_0.M65K.pathway.tsv.gz
10:34:16 [main] INFO  org.biojava.nbio.genome.parsers.gff.GFF3Reader - Reading: /tmp/gene_models_main.gff3
## INVALID: ID in this GFF record is not a valid LIS identifier:
## INVALID: lotja.MG20.gnm3.Lj0 protein_coding  exon    159887798       159887899       100.0   .       ID=known_Npl.mrna1.exon1;Name=known_Npl:3;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 1 101 +
```

**Comment by adf-ncgr** [comment]
> Caused by: java.lang.RuntimeException: GFF line does not include ID: lupal.Amiga.gnm1.Lalb_chloroplast_genome   Geneious        region  0       151915  0.0     0       Is_circular=true
>         at org.intermine.bio.dataconversion.AnnotationFileConverter.processGFF3File(AnnotationFileConverter.java:443)

seemingly these 2 childless "region" features (one for chloroplast and one for mitochondrion) are there for the sole purpose of declaring their circularity. Nevertheless, on the principle of no gff-declaration without IDentification, I've added IDs so they can be loaded. Someday circular molecules will be treated by genome browsers with the respect they deserve

**Comment by adf-ncgr** [comment]
> And finally (for these):
> 
> ```
> ## Validating annotation collection Wm82.gnm2.ann2.BG1Q with gensp=glyma
> ## Required file types:
> ##    gene_models_main.gff3.gz
> ##    protein.faa.gz
> ##    cds.fna.gz
> ##    mrna.fna.gz
> ## Optional file types:
> ##    legfed_v1_0.M65K.gfa.tsv.gz
> 10:36:13 [main] INFO  org.biojava.nbio.genome.parsers.gff.GFF3Reader - Reading: /tmp/gene_models_main.gff3
> ## INVALID: ID in this GFF record is not a valid LIS identifier:
> ## INVALID: glyma.Wm82.gnm2.ann2.Gm01   Gnomon  gene    -53819  -51941  0.0     .       ID=gene0;Dbxref=GeneID:10
> ```

This is the NCBI annotation that has never been properly LIS-ified. I'd say handling of NCBI genomes probably deserves its own issue (#110) if it's something we really want to tackle (and there may well be reasons to do so).

**Comment by adf-ncgr** [comment]
> ## Validating annotation collection MG20.gnm3.ann1.WF9B with gensp=lotja
> ## Required file types:
> ##    gene_models_main.gff3.gz
> ##    protein.faa.gz
> ##    cds.fna.gz
> ##    mrna.fna.gz
> ## Optional file types:
> ##    legfed_v1_0.M65K.gfa.tsv.gz
> ##    legfed_v1_0.M65K.pathway.tsv.gz
> 10:34:16 [main] INFO  org.biojava.nbio.genome.parsers.gff.GFF3Reader - Reading: /tmp/gene_models_main.gff3
> ## INVALID: ID in this GFF record is not a valid LIS identifier:
> ## INVALID: lotja.MG20.gnm3.Lj0 protein_coding  exon    159887798       159887899       100.0   .       ID=known_Npl.mrna1.exon1;Name=known_Npl:3;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 1 101 +

Should be fixed, but let me know if still problematic.

**Comment by adf-ncgr** [comment]
actually, hold off on lupal.Amiga, I just realized the IDs that were coined by the script will fail the "must look like an LIS ID" test. Usually they inherit their LIS-i-ness from their parents, but these didn't have parents.

**Comment by sammyjava** [comment]
> > Caused by: java.lang.RuntimeException: GFF line does not include ID: lupal.Amiga.gnm1.Lalb_chloroplast_genome   Geneious        region  0       151915  0.0     0       Is_circular=true
> > at org.intermine.bio.dataconversion.AnnotationFileConverter.processGFF3File(AnnotationFileConverter.java:443)
> 
> seemingly these 2 childless "region" features (one for chloroplast and one for mitochondrion) are there for the sole purpose of declaring their circularity. Nevertheless, on the principle of no gff-declaration without IDentification, I've added IDs so they can be loaded. Someday circular molecules will be treated by genome browsers with the respect they deserve

The Rodney Dangerfield of genomic features.

**Comment by sammyjava** [comment]
``` 
## Validating annotation collection Wm82.gnm2.ann2.BG1Q with gensp=glyma
```
> This is the NCBI annotation that has never been properly LIS-ified. I'd say handling of NCBI genomes probably deserves its own issue (#110) if it's something we really want to tackle (and there may well be reasons to do so).

Roger that, I'll switch to Wm82.gnm2.ann1.

**Comment by sammyjava** [comment]
Looks like you still have work to do on MG20:
```
## Validating annotation collection MG20.gnm3.ann1.WF9B with gensp=lotja
## lotja.MG20.gnm3.ann1.WF9B.gene_models_main.gff3.gz
07:16:22 [main] INFO  org.biojava.nbio.genome.parsers.gff.GFF3Reader - Reading: /tmp/gene_models_main.gff3
## INVALID: ID in this GFF record is not a valid LIS identifier:
## INVALID: lotja.MG20.gnm3.Lj4 protein_coding  gene    28879010        28884533        0.0     .       ID=gi|197209811|dbj|AB433810.1|.path1;Name=gi|197209811|dbj|AB433810.1|.path1;Type="protein_coding"
```

**Comment by sammyjava** [comment]
And Amiga still breaks, now because type=region is not supported. What would this be in the SO? I don't have anything in the data model to handle it, unless I just call it a generic SequenceFeature, which I could do just to be able to load it. I guess I could also update the loader to toss certain types. Or we can just delete these records.
```
Caused by: : java.lang.RuntimeException: GFF3 type region is not associated with a class in the featureClasses Map.
```

**Comment by sammyjava** [comment]
Oh forget it, it's those two organelles. I'm just going to yank them from my copy of the file and move on.
```
lupal.Amiga.gnm1.Lalb_chloroplast_genome        Geneious        region  1       151915  .       +       0       ID=lupal.Amiga.gnm1.ann1.region-1;Is_circular=true
lupal.Amiga.gnm1.Lalb_mitochondrion     GeSeq   region  1       405575  .       +       0       ID=lupal.Amiga.gnm1.ann1.region-2;Is_circular=true
```

**Comment by adf-ncgr** [comment]
looks like region is the ur-SO term: http://www.sequenceontology.org/browser/current_release/term/SO:0000001
more normally, these would be handled as 
##sequence-region 
"pragmas" ("optional, but strongly encouraged"), but I think this is being given an actual feature just in order to have the Is_circular attribute. Probably the "right" way to handle them for loading would just be to have an indication on Chromosome if it is circular and update the appropriate one (ie not create a sequencefeature for these). Practically speaking I think we can assume plant genomes will have circular organelles and straight nuclear chromosomes. But when NodFed includes symbionts we'll have circular genomes coming out of our nodules!

**Comment by sammyjava** [comment]
FYI I just blew away those few `gi` records locally in MG20 so I can get legumemine moving on. Maybe you'll do the same but I didn't upload them to the mother ship.

**Comment by sammyjava** [comment]
Closing this as I have a full-scale annotations validation issue coming.
