### ISSUE TITLE
new dataset: pisum sativum expression atlas

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#114]
not all that new, but one that we should incorporate when happy with the new procedures (and/or as part of testing said procedures):
Full-length de novo assembly of RNA-seq data in pea (Pisum sativum L.) provides a gene expression atlas and gives insights into root nodulation in this species
https://onlinelibrary.wiley.com/doi/10.1111/tpj.12967
read data available:
https://www.ncbi.nlm.nih.gov/bioproject/267198

**Comment by adf-ncgr** [comment]
Will assign @el239 when he has accepted the github invite.

**Comment by sammyjava** [comment]
Any update on this analysis @el239 @adf-ncgr ? Just curious.

**Comment by adf-ncgr** [comment]
looks like this very old issue is nearly ready to be handled! @el239 did you get things worked out for access to the data store? If so, feel free to post this one up there.

**Comment by el239** [comment]
Hello, very sorry for the rather later update. This dataset is ready, but I have not yet sorted out datastore access. Will update when it is ready.

**Comment by el239** [comment]
This dataset is now available on the datastore.
