### ISSUE TITLE
descriptors for phytozome_10_2 gene families

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#115]
I think we had discussed the need for this once upon a time, and because I ran into the absence of these descriptors when working with MedicMine I've gone ahead and generated them; but I am not sure exactly where we want to put them to get them in the next build of stuff that uses them. It may become a moot point in the future as I'm hoping that the next round of building our legume families will take care of the issues that makes me keep these hanging around. Anyway, the ones that I calculated are currently residing here:
/erdos/legumeinfo/data/private/gene_families/phytozome_10_2/AHRD/all.ahrd.tsv.cleaned 

I think this is consistent with the corresponding file legume.genefam.fam1.M65K.info_annot_ahrd.tsv.gz
but we can certainly rename/package it differently as desired.

**Comment by sammyjava** [comment]
Move to the LIS DS? Or should I hold off on loading phytozome gene families in general? It's kind of spotty which annotation collections have them.

**Comment by adf-ncgr** [comment]
yeah, I think holding off is fine. It may be that in the next round of gene family building we will address the issues that have caused me to want to keep these around (lack of support for species-specific gene families, inclusion of only selected genes from outgroup species).

**Comment by sammyjava** [comment]
OK I'll close this, then.
