### ISSUE TITLE
Fix marker coordinates for Zhao_Teng_2017

### ISSUE THREAD

**Issue by cann0010** [legumeinfo/datastore-issues#117]
There were several problems with the markers in Glycine/max/markers/Wm82.gnm2.mrk.Zhao_Teng_2017/ :
- The coordinates were assumed to be with Wm82.gnm2, whereas the paper reported the coordinates with respect to Wm82.gnm1. However, we WANT the coordinates with respect to Wm82.gnm2, for use in ZZBrowse.
- The markers in the DS (and SoyBase) looked like RS:7622492, whereas in the paper they had the form rs7622492 (lowercase rs, no colon).
- The manuscript reports only 13 markers (associated with soybean cyst nematode resistance), whereas the marker set in the DS had 20 markers. The other seven markers come from Zhao_Han_2015 (doi: 10.1111/tpj.12810), for association with Sclerotinia resistance. To reduce confusion, it is best that these markers be moved to a new collection, Wm82.gnm1.mrk.Zhao_Han_2015 ... unless we are able to find the complete SLAFSeq marker set.

Changes made: 
- There is a new collection, Wm82.gnm1.mrk.Zhao_Teng_2017, with the correct markers and coordinates.
- The collection Wm82.gnm2.mrk.Zhao_Teng_2017 has marker positions projected into Wm82.gnm2.
- The seven "extra" markers have been removed. Those will be put in a new collection Wm82.gnm1.mrk.Zhao_Han_2015 (to be a separate issue).
- The filenames are now ...Zhao_Teng_2017.gff3 rather than ...SLAFSeq.gff3
- Markers have the form rs7622492
- Marker names in Glycine/max/genetic/mixed.gwas.Zhao_Teng_2017 have been changed to the form rs7622492

I'll mention that the reason for focusing on this collection is that it has some results that are important for the work of student Samuel Clouse on resistance to soybean cyst nematode. @svengato - We'd like the markers with Wm82.gnm2 coordinates used in ZZBrowse, replacing the current set for Zhao_Teng_2017.

Noting here for documentation of the changes. Will post this issue for review by @sammyjava or @svengato. One of you can close if it looks OK, or else let me know and I'll close.

**Comment by svengato** [comment]
I updated the soybean GWAS and combined GWAS-QTL data on both development and production ZZBrowse. The marker names for Zhao_Teng_2017 now look like rs7622492. There are also new soybean cyst nematode data from Tran_Steketee_2019, with marker names like ss715594958. Let me know if anything is incorrect.

**Comment by cann0010** [comment]
Thank you, @svengato. I was able to check the new data in soybean GWAS and bean GWAS. Attempting it again though (several times), I am getting the Proxy Error message upon hitting Submit.

**Comment by cann0010** [comment]
@svengato It's working for me again. I'll experiment with patience :-)
The results for nematode resistance are pretty much what we were hoping to see. Some nice biology.
Closing the parent issue now ...

**Comment by adf-ncgr** [comment]
@cann0010 just FWIW, we've talked about a possible rebuilding of ZZBrowse from the ground up to try to deal with some of the performance issues; but there may also be some lower-hanging optimizations (@svengato did we ever figure out what the connection was between my GCV upgrade and the odd behaviors that ensued?)

**Comment by svengato** [comment]
No (at least I do not understand it).

**Comment by adf-ncgr** [comment]
OK, I'll create a new issue (in ZZBrowse repo) for discussion on the GCV symbiosis gone wrong mystery.
