### ISSUE TITLE
G2333_x_G19839.map.Checa_Blair_2008 lacks markers

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#123]
The description refers to 149 mapped markers. But we don't have them.

**Comment by sammyjava** [comment]
So, I think I've discovered a mistake in my chado exports. This QTL collection lists a bunch of QTLs that are not in the paper - because they happened to be located on the same LGs. They are actually from different papers. This paper is about Plant height, Internode length, Climbing ability, and Branch number. The extra QTLs (root characteristics and seed coat tannin) are from other experiments under the Blair umbrella. So I'll remove them from this particular paper/collection.

**Comment by sammyjava** [comment]
This is what the QTL file looks like after I've recovered the QTL names from the paper, which are different in terms of M-N suffixes from the chado export, which is misleading IMO. This is what I think we should be doing: reporting what's in the paper. I presume you or someone measured the QTL spans from the map image, and doing so for the markers was too much work so we lack a mrk.tsv file in the map collection. But they were nice enough to report the LG lengths on the image. I can yank the QTL-peak markers for the mrk.tsv file in the map collection. I'm motivated to update all the phavu maps and QTL studies to be consistent with their publications. It's mostly renaming, not a ton of measuring off images.
```
#qtl_identifier trait_name      linkage_group   start   end
Plh1-1  Plant height    B03     12      21
Plh1-2  Plant height    B04     33      50
Plh1-3  Plant height    B04     98      105
Plh1-4  Plant height    B08     85      90
Plh2-1  Plant height    B04     90      105
Plh2-2  Plant height    B04     31      48
Plh2-3  Plant height    B11     24      32
Int1    Internode length        B03     21      37
Int2    Internode length        B04     42      50
Int3    Internode length        B04     90      102
Int4    Internode length        B04     26      38
Cab1-1  Climbing ability        B04     90      105
Cab1-2  Climbing ability        B04     44      49
Cab1-3  Climbing ability        B05     13      21
Cab1-4  Climbing ability        B07     9       25
Cab1-5  Climbing ability        B10     83      90
Cab1-6  Climbing ability        B11     25      41
Cab2-1  Climbing ability        B04     90      105
Brn1    Branch number   B04     91      105
```
![Checa_Blair_2008](https://user-images.githubusercontent.com/5657219/191130581-a878a98c-8855-492d-91d8-d80f5872b0a8.png)

**Comment by sammyjava** [comment]
@cann0010 you're off the hook, I'm going to grab relevant markers from figures for these maps that are missing markers. It's pretty easy with Gimp. I plan to rename the LGs to the original names for all of the phavu QTL studies and get the relevant maps straightened out.

**Comment by cann0010** [comment]
Much appreciated. Gimp - that's some strong magic.
I am finally easing back into work; will be back in Ames Friday.

**Comment by sammyjava** [comment]
(I may do the rest of the markers sometime, it's not that huge of a project.)
