### ISSUE TITLE
expression data for cowpea pangenome

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#127]
per discussion, we have TPM data for both the set of samples from a given cultivar mapped back to its own genome as well as all mapped to the main reference genome. You'll find the latter under:
/erdos/adf/nf-core/rnaseq/cowpea_pangenome_rnaseq.all_together_markdups/star_salmon
and the former under folders in the same location (one for each of the non-reference cultivars):
cowpea_pangenome_rnaseq.CB5-2
cowpea_pangenome_rnaseq.Sanzi
cowpea_pangenome_rnaseq.Suvita2
cowpea_pangenome_rnaseq.TZ30
cowpea_pangenome_rnaseq.UCR779
cowpea_pangenome_rnaseq.ZN016

since you volunteered to datastorify these, I happily pass the buck to you @sammyjava ! Just let me know if you have any questions...

**Comment by adf-ncgr** [comment]
need to check whether I updated metadata, there was an issue with a couple of labels having been swapped in the SRA submission that Tim helped resolve, I think I applied it locally as well but will verify

**Comment by adf-ncgr** [comment]
OK, I just figured out what was confusing me about this and the correction made by Tim at NCBI. The way that they submitted the data all of the experiments for a given lines link to the same sample accession, while the experiment descriptors give the correct information about tissue and treatment. So please do use the metadata that has been corrected locally in any of the files under /erdos/adf/nf-core/rnaseq/cowpea_pangenome_rnaseq.CB5-2/samplesheet
(and similarly for the other accessions which didn't require any corrections, although they all have a similar issue in that the same sample accession is used for all the different experiments, so it is the experiment descriptor that has the appropriate metadata).

**Comment by sammyjava** [comment]
These expression studies are all in CicerMine.
