### ISSUE TITLE
Missing Phavu QTL dataset?

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#130]
While updating data for ZZBrowse, I noticed that there are nine new Phavu QTL datasets in the data store (no problem, I will add them), but one that used to exist is no longer there,
  Phaseolus/vulgaris/qtl/ICABunsi_x_SXB405.gen.Parker_BernyMierYTeran_2020/
(the "gen" would now be "qtl"). Is this a mistake?

**Comment by sammyjava** [comment]
Yeah, here's the comment on the README deletion:

https://github.com/legumeinfo/datastore-metadata/commit/1a64967a8b931487a026e33f1f5129afd6cbbbd2

Not a QTL study.
