### ISSUE TITLE
medtr.A17.gnm5.ann1_6.L2RX.legfed_v1_0.M65K.gfa.tsv.gz has invalid protein IDs

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#132]
New validation piece:
--------------------------------------------------------------------------------
### Validating medtr collection A17.gnm5.ann1_6.L2RX
 - medtr.A17.gnm5.ann1_6.L2RX.gene_models_main.gff3.gz
10:54:06 [main] INFO  org.biojava.nbio.genome.parsers.gff.GFF3Reader - Reading: /tmp/temp.gff3
 - medtr.A17.gnm5.ann1_6.L2RX.protein.faa.gz
 - medtr.A17.gnm5.ann1_6.L2RX.cds.fna.gz
 - medtr.A17.gnm5.ann1_6.L2RX.mrna.fna.gz
 - medtr.A17.gnm5.ann1_6.L2RX.iprscan.gff3.gz
10:54:28 [main] INFO  org.biojava.nbio.genome.parsers.gff.GFF3Reader - Reading: /tmp/temp.gff3
 - medtr.A17.gnm5.ann1_6.L2RX.legfed_v1_0.M65K.gfa.tsv.gz
### INVALID: medtr.A17.gnm5.ann1_6.MtrunA17Chr1g0209791	legfed_v1_0.L_GRYW1V	medtr.A17.gnm5.ann1_6.MtrunA17Chr1g0209791	2.4e-41	143.8	143.6
 - medtr.A17.gnm5.ann1_6.L2RX.legfed_v1_0.M65K.pathway.tsv.gz
 - medtr.A17.gnm5.ann1_6.L2RX.phytozome_10_2.HFNR.gfa.tsv.gz

**Comment by adf-ncgr** [comment]
should now be fixed
