### ISSUE TITLE
Load Arachis stenosperma genome

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#133]
https://www.ncbi.nlm.nih.gov/data-hub/genome/GCA_014773155.1/
https://www.ncbi.nlm.nih.gov/bioproject/PRJNA610652/

**Comment by sammyjava** [comment]
Assigning @cann0010 and @adf-ncgr to encourage them to assign to someone else. :)

**Comment by cann0010** [comment]
Assignment accepted. I had started the collection a while ago, so I'll go ahead and finish it.

**Comment by cann0010** [comment]
Closing this issue. A new one has been opened, with checklist:
https://github.com/legumeinfo/datastore-issues/issues/142
