### ISSUE TITLE
Five annotations collections need a-fixin' 

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#134]
- [x] **Validating lotja collection MG20.gnm3.ann1.WF9B**
INVALID: Gene ID gi|197209811|dbj|AB433810.1|.path1 in lotja.MG20.gnm3.ann1.WF9B.phytozome_10_2.HFNR.gfa.tsv.gz is not a valid LIS identifier:
INVALID: Protein ID gi|197209811|dbj|AB433810.1|.path1.1 in lotja.MG20.gnm3.ann1.WF9B.phytozome_10_2.HFNR.gfa.tsv.gz is not a valid LIS identifier:

- [x] **Validating glyma collection Wm82_ISU01.gnm2.ann1.FGFB**
INVALID: Required file glyma.Wm82_ISU01.gnm2.ann1.FGFB.legfed_v1_0.M65K.gfa.tsv.gz is not present in Wm82_ISU01.gnm2.ann1.FGFB
INVALID: Missing required files.

- [x] **Validating glyma collection Wm82_ISU01.gnm2.ann1.FGFB**
INVALID: glyma.Wm82_ISU01.gnm2.ann1.FGFB.gene_models_main.gff3.gz record ID attribute is missing or invalid:
`glyma.Wm82_ISU01.gnm2.Gm01	phytozomev13	CDS	311075	311213	0.0	0	ID=GmISU01.01G001200.1.CDS.18;Parent=GmISU01.01G001200.1;pacid=53729792;`
INVALID: glyma.Wm82_ISU01.gnm2.ann1.FGFB.gene_models_main.gff3.gz record parent attribute is invalid; does the file need sorting?
`glyma.Wm82_ISU01.gnm2.Gm01	phytozomev13	CDS	311075	311213	0.0	0	ID=GmISU01.01G001200.1.CDS.18;Parent=GmISU01.01G001200.1;pacid=53729792;`
INVALID: GFA file contains gene ID glyma.Wm82_ISU01.gnm2.ann1.GmISU01.12G003800 that is not present in the gene models GFF file.

- [x] **Validating glyma collection Wm82.gnm2.ann2.BG1Q**
INVALID: glyma.Wm82.gnm2.ann2.BG1Q.gene_models_main.gff3.gz record ID attribute is missing or invalid:
```glyma.Wm82.gnm2.ann2.Gm01	Gnomon	gene	-53819	-51941	0.0	.	ID=gene0;Dbxref=GeneID:100808170;Name=LOC100808170;gbkey=Gene;gene=glyma.Wm82.gnm2.ann2.LOC100808170;gene_biotype=lncRNA```
INVALID: GFA file contains gene ID glyma.Wm82.gnm2.ann2.LOC547631 that is not present in the gene models GFF file.
INVALID: GFA file contains protein ID glyma.Wm82.gnm2.ann2.NP_001235628.1 that is not present in the protein FASTA file(s).

- [x] **Validating glyma collection Hwangkeum.gnm1.ann1.1G4F**
INVALID: Required file glyma.Hwangkeum.gnm1.ann1.1G4F.mrna.fna.gz is not present in Hwangkeum.gnm1.ann1.1G4F
INVALID: Missing required files.

- [x] **Validating cerca collection ISC453364.gnm1.ann1.HZJM**
Now the gene models GFF is empty!

**Comment by sammyjava** [comment]
(I did fix some other stuff, but these are mostly missing files plus some GFA funk.)

**Comment by sammyjava** [comment]
Well I'd say we move it off of the Datastore in the meantime, unless you want to make it conformant in reasonably short order. I'm on a 100% Conformance Crusade now. (Partly because I've scripted LegumeMine loading to load all genomes and annotations so it's a complete representation of those public collections, but I think it's a good idea, anyway.)

**Comment by adf-ncgr** [comment]
If you have become the Caped Conformance Crusader, does it mean you will start scaling the walls outside the building instead of letting us drive you up the wall on the inside?

**Comment by adf-ncgr** [comment]
regarding the error from lotja collection MG20.gnm3.ann1.WF9B I suppose the easiest thing to do would be to make the IDs (in gff file and related):
lotja.MG20.gnm3.ann1.gi|197209811|dbj|AB433810.1|.path1
etc.
presumably the original naming sin here is from something like gmapping known sequences from genbank.
Is that stomachable?

**Comment by cann0010** [comment]
My first-pass assessment and recommendations:

```
Problem in lotja collection MG20.gnm3.ann1.WF9B:
The fix: There's one bad gene ID. Fix it throughout the collection.

Problem in glyma collection Wm82_ISU01.gnm2.ann1.FGFB: 
The fix: Move file glyma.Wm82.gnm2.ann2.BG1Q.gene_models_original.gff3.gz off to the side**.

Problem in glyma collection Hwangkeum.gnm1.ann1.1G4F:
The fix: Generate a new mrna file.

Problem in cerca collection ISC453364.gnm1.ann1.HZJM:
The fix: Generate a new gfa.tsv file. @adf-ncgr 
```

** For the funky gff3 in Wm82_ISU01.gnm2.ann1.FGFB, what does "off to the side" mean?
How about establishing an "xtra" directory for stuff that is important to keep in the collection, buyer beware?

I can work on tackling most of these, but probably not before Thursday.

**Comment by adf-ncgr** [comment]
I think the issue with Wm82_ISU01.gnm2.ann1.FGFB was just the gfa file? 
FWIW, I've got that and the mrna file in progress for the Hwangkeum; will do cerca too.

**Comment by sammyjava** [comment]
_Extra files_ like glyma.Wm82.gnm2.ann2.BG1Q.gene_models_original.gff3.gz are fine. I only validate the required files, plus optional files that I load if present, like the iprscan gff or phytozome gfa. So no need to move glyma.Wm82.gnm2.ann2.BG1Q.gene_models_original.gff3.gz anywhere unless you want  to.

Good eye on the lotja MG20 phytozome GFA, I've fixed it by yanking that one line. I should have looked.

**Comment by adf-ncgr** [comment]
FYI the lotja gene referenced in the GFA is present elsewhere (e.g. GFF, probably fasta files). Not sure if it will continue to cause heartache

**Comment by sammyjava** [comment]
> I think the issue with Wm82_ISU01.gnm2.ann1.FGFB was just the gfa file? FWIW, I've got that and the mrna file in progress for the Hwangkeum; will do cerca too.

Yeah, just a missing GFA file, no biggy. Thanks!

The only significant one here is Wm82.gnm2.ann2.BG1Q being totally non-LIS. I can just avoid it but I think we shouldn't have it in the public Datastore until we make it meet LIS specs.

**Comment by sammyjava** [comment]
> FYI the lotja gene referenced in the GFA is present elsewhere (e.g. GFF, probably fasta files). Not sure if it will continue to cause heartache

Yeah, I had yanked those earlier, locally, but had just grabbed the phytozome file today. I should have checked. I'll upload the fixed files en masse. Validates now.

**Comment by sammyjava** [comment]
Argh @adf-ncgr couldn't figure out why I can't tabix the lotja GFF, but it's permissions as usual:
```
-rw-r--r--  1 adf      staff      91417 Jul  6 18:36 lotja.MG20.gnm3.ann1.WF9B.gene_models_main.gff3.gz.tbi
```
I'll let you tabix the GFF.

**Comment by adf-ncgr** [comment]
huh, wonder why that one file would have different permissions. anyway, it's fixed and I've updated the md5 sums (assuming this was the last change needed)

**Comment by adf-ncgr** [comment]
cerca collection ISC453364.gnm1.ann1.HZJM seems not to have gene records in its gff file, only mRNA and descendants. Thus the gfa file can assign proteins to families, but not genes unless we decide to add them. The mRNA records are currently named like genes (ie no isoform suffixes). I believe there's a much improved cerca.ISC453364.gnm3 and annotations waiting in the wings so not sure how much retroactive standardization is really warranted, but I can add gene records if desired. We probably do need some sort of agreement on how best to phase out old versions (leaving them in the datastore but not necessarily forcing ourselves to keep them up to date with the latest trends)

**Comment by sammyjava** [comment]
I think a gene_models_main.gff should have gene records. Otherwise we have no genes from that annotation, which is just going to annoy everyone. So please do the appropriate additions/renames.

**Comment by sammyjava** [comment]
@adf-ncgr Wm82_ISU01.gnm2.ann1.FGFB has additional problems that I forgot to list, I guess. New checkbox.

**Comment by adf-ncgr** [comment]
OK, with respect to Wm82_ISU01.gnm2.ann1.FGFB I think I should punt to @cann0010 since it may have been a result of his ds_souschef protocol which it would be good to have robustified if so. I didn't pull this one in, in any case so not sure what the history is.

**Comment by cann0010** [comment]
I think the GFFs in Wm82_ISU01.gnm2.ann1.FGFB are fixed now. The problem (or A problem) was due to mis-sorting. I was using the appealingly simple approach in sort_gff.pl, but that sorts features by chromosome, then position, then feature type; and this doesn't work for interleaved genes. I am going to fall back to the third-party gff3sort.pl.

**Comment by sammyjava** [comment]
We're down to add genes+GFA to cerca collection ISC453364.gnm1.ann1.HZJM and get rid of (I think) glyma collection Wm82.gnm2.ann2.BG1Q until a conformant version is built.

**Comment by sammyjava** [comment]
Wm82.gnm2.ann2.BG1Q moved to private, README removed from metadata.

**Comment by adf-ncgr** [comment]
I'm confused about the interleaved genes comment. We need to have our data sorted by chromosome/position for tabix indexing. The sort by type is to try to ensure that parents also precede children. Only in cases where a child feature claims to be outside the bounds of its parents should there be a real conflict between the two competing requirements. But interleaved genes shouldn't be an issue per se (ie it should be fine to have them interleaved if that's what positional sorting demands).

**Comment by cann0010** [comment]
@adf-ncgr - A naive positional sort may give a technically compliant GFF (I am not sure), but check-disorder.pl from gff3sort reports 1323 "disordered" genes (e.g. 20G086800) in positionally sorted glyma.Wm82_ISU01.gnm2.ann1.FGFB.gene_models_main.gff3 ... and that disorder results in incorrect results when I apply my hash_into_gff_id.pl.  I'll need to check WHY, but I think it is because my script pays attention to parentage and presumes that child features are contiguous under their parent.

**Comment by adf-ncgr** [comment]
I don't think we can presume that child features are contiguous under the parents unless we disallow overlapping models or give up on tabix indexing (which would break the plan for direct serving of files under JBrowse2). But I agree that having parents precede children is a good thing, even though I don't think the gff3 spec actually requires it (I could be wrong about that). I forget why I decided gff3sort wasn't suitable, but it might have been something like this.

**Comment by sammyjava** [comment]
FWIW mine loading only cares that parents precede children, not whether there's anything in between them.

**Comment by adf-ncgr** [comment]
cerca.ISC453364.gnm1.ann1.HZJM should be ready to go. I'll note that in addition to not having gene records (which I added) the gene_models_main file had CDS records but no exons, presumably because no attempt was made to look for non-coding portions of transcripts. I left that as is, hopefully it is innocuous.

**Comment by adf-ncgr** [comment]
@cann0010 looks like this issue of sorting still needs to be sorted out:
[adf@lis-stage /usr/local/www/data/v2/Glycine/max/annotations/Wm82_ISU01.gnm2.ann1.FGFB]$ tabix -p gff glyma.Wm82_ISU01.gnm2.ann1.FGFB.gene_models_main.gff3.gz
[E::hts_idx_push] Unsorted positions on sequence #1: 103572 followed by 103222
tbx_index_build failed: glyma.Wm82_ISU01.gnm2.ann1.FGFB.gene_models_main.gff3.gz

**Comment by cann0010** [comment]
@adf-ncgr Yep. I concede that gff3sort is not compatible with tabix indexing. I have re-added the positional sorting routine to hash_into_gff_id.pl and yanked the code that presumed contiguous child features under parents. The latest glyma.Wm82_ISU01.gnm2.ann1.FGFB.gene_models_main.gff3.gz did apparently index correctly. It is updated in that collection.

**Comment by sammyjava** [comment]
I think this is done since I just promoted GlycineMine and the remaining one was glyma. :)

**Comment by sammyjava** [comment]
> cerca.ISC453364.gnm1.ann1.HZJM should be ready to go. I'll note that in addition to not having gene records (which I added) the gene_models_main file had CDS records but no exons, presumably because no attempt was made to look for non-coding portions of transcripts. I left that as is, hopefully it is innocuous.

Um, the gene models GFF is empty.
```
-rw-rw-r--    1 adf      staff          28 Nov 11 14:53 cerca.ISC453364.gnm1.ann1.HZJM.gene_models_main.gff3.gz
```

**Comment by sammyjava** [comment]
NOTE: I removed the contig records from `vigra.VC1973A.gnm7.ann1.RWBG.gene_models_main.gff3.gz` since the mine loader errors on those and we normally don't include them in GFFs, being loaded from the genomic FASTA.

**Comment by adf-ncgr** [comment]
well that's weird. something must have clobbered it after the last time I touched it, because the recorded checksum didn't match, but does now after I applied the same command recorded in the CHANGES file. Legume poltergeist? You may have to re-remove contig records.

**Comment by sammyjava** [comment]
Nope no contigs in that one, thanks!

**Comment by sammyjava** [comment]
I'm gonna close this, I've loaded all the mines since this was posted and it got pretty off topic anyway. :)
