### ISSUE TITLE
VC1973A.gnm7.ann1.RWBG lacks GFA

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#140]
### INVALID: Missing required files.

**Comment by sammyjava** [comment]
@cann0010 I think we should have some sort of notification system (like your recent email but perhaps a bit more sticky like an issue here) so that it isn't me that discovers, say, annotation collections lack a GFA when I'm building a mine. GFAs should be built when a new annotation is added. I think this extends to other situations as well.

The reason I find out about a new collection is that the README appears in datastore-metadata, which is a great way for me to discover it. Then I download the new collection and lo and behold it fails validation and I need help.

**Comment by adf-ncgr** [comment]
thanks, this annotation hasn't been processed via AHRD either, so there's a bit more to do before you'll want to try dealing with it. I'm not sure if we want to post things to the datastore before some of these things have been done, but also don't want to be the bottleneck.

**Comment by cann0010** [comment]
@sammyjava Agree. How about an issue with checklist for each new collection or collection-batch that will require actions from multiple people? With each turn of the crank, we should also try to improve the protocol description and the automation.

For genome+annotation collections, what are the downstream actions?
Calculate AHRD
Calculate GFA
Add to pan-gene set?
Load mine
Add BLAST targets
GCV steps?
Maybe remap markers (for new reference genome)
Maybe update ZZBrowse (for new reference genome)
Other?

**Comment by adf-ncgr** [comment]
@cann0010 I like the issue+checklist idea; I think we could set up an issue template for this purpose, and maybe eventually have different sets of steps (in different templates) associated with different types of dataset. 

a couple of additions to your suggested list:
update the jekyll collections listing
update browser configs
perform whole genome alignments(?)

**Comment by sammyjava** [comment]
Plus, of course, validating the newly created collections (which may include synteny and marker collections if we've got a new genome). Since even if things have been done, mistakes may have been made, like with IDs.
```
[shokin@lis ~]$ validate-genome-collection v2/Vigna/radiata/genomes/VC1973A.gnm7.SB53/
--------------------------------------------------------------------------------
### Validating vigra collection VC1973A.gnm7.SB53
 - vigra.VC1973A.gnm7.SB53.genome_main.fna.gz
### VALID
[shokin@lis ~]$ validate-annotation-collection v2/Vigna/radiata/annotations/VC1973A.gnm7.ann1.RWBG/
--------------------------------------------------------------------------------
### Validating vigra collection VC1973A.gnm7.ann1.RWBG
### INVALID: Required file vigra.VC1973A.gnm7.ann1.RWBG.legfed_v1_0.M65K.gfa.tsv.gz is not present in VC1973A.gnm7.ann1.RWBG
### INVALID: Missing required files.
```

**Comment by adf-ncgr** [comment]
OK, the gfa file and updates associated with AHRD-ification of the gff are complete and on the datastore. I have still to add the new checklist, but in the context of what remains to be done for this work in progress genome, I'll deal with GCV and BLAST, and will get @svengato working on the ZZBrowse upgrade. @sammyjava you will want to create a pathway file before doing the mine loading.

**Comment by cann0010** [comment]
Thanks, Andrew.

I propose that we flesh out the protocols here:
https://github.com/legumeinfo/datastore-specifications/tree/main/PROTOCOLS

The README may be under-structured, but presumably it can be whipped into shape. Or it could be split out into a collection of documents if there's good reason to do so.

**Comment by sammyjava** [comment]
Thank you sir. I'll create a new issue for the work on protocol documentation.
