### ISSUE TITLE
New Arachis stenosperma genome

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/datastore-issues#142]
### Main steps for adding new genome and annotation collections

# Genus/species/collection names: 
What are the collection types and names?
- Arachis/stenosperma/genomes/V10309.gnm1.PFL2
- (No annotations yet)

- [x] Add collection(s) to the Data Store
- [x] Validate the README(s)
- [x] Update about_this_collection.yml
- [ ] Calculate AHRD functional annotations 
- [ ] Calculate gene family assignments (.gfa) 
- [ ] Add to pan-gene set 
- [ ] Load relevant mine 
- [ ] Add BLAST targets 
- [ ] Incorporate into GCV 
- [ ] Update the jekyll collections listing 
- [ ] Update browser configs

**Comment by adf-ncgr** [comment]
I think this is now superseded by #189 so closing it
