### ISSUE TITLE
most Vigna/unguiculata genomes/annotations still need READMEs

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#15]
I think the cowpeapan genomes were done by our curator (me) in minimalist mode and should probably get transcript files added in (as well as the files including the nonprimary transcripts, if they have splice variants)

also of note, non-ASCII characters in :
https://legumeinfo.org/data/v2/Vigna/unguiculata/genomes/IT97K-499-35.gnm1.QnBW/README.IT97K-499-35.gnm1.QnBW.yml
https://legumeinfo.org/data/v2/Vigna/unguiculata/annotations/IT97K-499-35.gnm1.ann1.zb5D/README.IT97K-499-35.gnm1.ann1.zb5D.yml
are not displaying in the browser though seemingly OK when viewed in the files; probably we need to specify character encoding in http headers or something like that.

**Comment by sammyjava** [comment]
Every HTML page should have `<meta charset="UTF-8">` inside the HEAD nowadays, because you can't trust old Apache httpd to send it. Especially not Apache httpd running on FreeBSD. :)

**Comment by sammyjava** [comment]
I don't see anyone volunteering for this. I create READMEs for the genetic data but can't be bothered to build them for the annotations and genomes. I don't need them for the mines. Closing.
