### ISSUE TITLE
undo the gensp. prefixing of Name in all gene_models_main files

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#16]
I guess this is what we've decided for now (Name = unchanged from origin, ID = fullyuck.Name). Doing this generally will fix #7

**Comment by sammyjava** [comment]
I do, in fact, strip the leading gensp. from Name when I curate for mine loading in the current round. If I miss one, it's on me.

**Comment by sammyjava** [comment]
Closing this, I handle this when it comes up, it will be "solved" when all mines have been updated.
