### ISSUE TITLE
Chamaecrista/fasciculata/annotations/MN87.gnm1.ann1.LWFM/chafa.MN87.gnm1.ann1.LWFM.gene_models_main.gff3.gz

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#170]

**Comment by adf-ncgr** [comment]
just like #169, except that there is no newer genome version  in this case

**Comment by StevenCannon-USDA** [comment]
We have a new genome assembly waiting in the wings. Should have the annotations soon. The old assembly and annotations can basically be ignored.

**Comment by sammyjava** [comment]
I've sent MN87 over to the annex where I see the shiny new genome awaits the light of day.
