### ISSUE TITLE
glyma.Zh13.gnm2.ann1.FJ3G.gene_models_main.gff3.gz is not sorted

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#172]
```
[convertFile] ## Validating glyma collection Zh13.gnm2.ann1.FJ3G
[convertFile]  - glyma.Zh13.gnm2.ann1.FJ3G.gene_models_main.gff3.gz
[convertFile] ## INVALID: glyma.Zh13.gnm2.ann1.FJ3G.gene_models_main.gff3.gz record parent attribute is invalid; does the file need sorting?
[convertFile] ## INVALID: glyma.Zh13.gnm2.Chr01      ShortStack      miRNA   -5336733        -5336711        0.0     .       ID=glyma.Zh13.gnm2.ann1.SoyZH13_miRNA_001-3p;Name=SoyZH13_miRNA_001-3p;Parent=glyma.Zh13.gnm2.ann1.SoyZH13_miRNA_001
[convertFile] ## INVALID: {Parent=glyma.Zh13.gnm2.ann1.SoyZH13_miRNA_001, ID=glyma.Zh13.gnm2.ann1.SoyZH13_miRNA_001-3p, Name=SoyZH13_miRNA_001-3p}
```

**Comment by sammyjava** [comment]
I'm not sure who to blame for this so I assigned it to both of you to pass the blame on. This blocks completing the current GlycineMine build.

**Comment by adf-ncgr** [comment]
I'll take a look. I am not liking the negative coordinates appearing in your snippet.

**Comment by adf-ncgr** [comment]
not sure why those coordinates looked negative in your log output, they were fine. But there was a sorting issue due to some transcript types that the sorting script wasn't accounting for and placing them before their Parent genes. Hopefully fixed now.

**Comment by sammyjava** [comment]
> not sure why those coordinates looked negative in your log output, they were fine. But there was a sorting issue due to some transcript types that the sorting script wasn't accounting for and placing them before their Parent genes. Hopefully fixed now.

Weird. That's BioJava featureI.toString() doing that. Strange.
