### ISSUE TITLE
RFO: update annotation GFFs to use Ensemble Plants / Plant Reactome gene names

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#179]
I'm wondering where we get our **Name** values in the annotation GFFs from. Dark places? I'm writing a pathway processor that matches our genes with Plant Reactome gene names, and I find that Ensemble Plants and Plant Reactome use the same names, which almost always do NOT match the **Name** attribute in our GFFs.

If one searches on an LIS gene name in Plant Reactome or Ensemble, one gets zero results. This makes me think using the Ensemble gene names in our annotation GFFs is a Good Thing For Users. (It doesn't affect anything else we do, we don't use gene names functionally.)

This of course matters, since NO OTHER RESOURCE uses LIS gene identifiers. The **Name** is actually where we can connect a gene in the LIS Datastore to that gene elsewhere, like Ensemble Plants and Plant Reactome.

Is there some OTHER external resource that DOES use our gene names which would compete with this proposal? We should NOT be making up gene names if they already exist elsewhere.

Examples:

| LIS | Ensemble / Plant Reactome |
| --- | --- |
| Glyma.08G085800 | GLYMA_08G085800 |
| Phvul.004G160000 | PHAVU_004G160000g |
| cajca.C.cajan_36043 | C.cajan_36043.1 |
| Aradu.16RQU | Aradu.16RQU. |
| Medtr7g090310 | MTR_7g090310 |
| tripr.gene3601 | Tp57577_TGAC_v2_gene3601 |
| *missing* | Psat2g004640 |

In the last case, our GFF is missing the Name attribute, but the secondary identifier from the full yuck matches the Ensemble / Plant Reactome name, so I'll go ahead and put it into the GFF Name attribute.

If folks agree to this proposal, I'll make it a task and update the **Name** attribute for all annotations that contain genes present in Ensemble Plants and/or Plant Reactome. (And do nothing with the other annotations until we find another external resource that references the same genes by name.)

**Comment by sammyjava** [comment]
Note that an added benefit of this update would be that I could link Plant Reactome and Ensemble Plants on the mine gene report pages. That seems like a nice thing to do.

**Comment by StevenCannon-USDA** [comment]
Strongly object. 

Ensembl/Reactome does their own (seemingly-arbitrary) munging, and I don't think there is a good reason for us to follow them.

At least in these cases from the examples above ...
```
GLYMA_08G085800
PHAVU_004G160000g
MTR_7g090310
```
... these names have apparently been changed by the Ensembl/Reactome by upper-casing and s/\./_/ and s/Medtr/MTR/

In general, our gene names come from the primary sources/repositories of the annotations. Where a name needs to be extracted or added to the GFF, I think in general it would come from the ID (sans DS prefix).

**Comment by sammyjava** [comment]
Thanks, so the answer is "yes, our names actually DO correspond to public repositories that our users may use." (This is new to me, I've literally never used an LIS gene name to reach another resource for that gene.)

In that case, I think I'd like to add ensembleName to our Gene data model using my own munging algorithm so I can link out to those resources, which has no impact on anything anyone is doing at LIS. I may add that to the GraphQL Gene type, though.

**Comment by sammyjava** [comment]
Clarification: I mean adding ensembleName on the fly with a post-processor, not touching the LIS GFFs.
