### ISSUE TITLE
Add Phaseolus coccineus genome from phytozome

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#182]
https://phytozome-next.jgi.doe.gov/info/Pcoccineus_v1_1

### Main steps for adding new genome and annotation collections

# Genus/species/collection names: 
What are the collection types and names? (currently awaiting full yuckification in private area of datastore)
- Phaseolus/coccineus/genomes/TBD
- Phaseolus/coccineus/annotations/TBD

- [ ] Add collection(s) to the Data Store
- [ ] Validate the README(s)
- [ ] Update about_this_collection.yml
- [ ] Calculate AHRD functional annotations 
- [ ] Calculate gene family assignments (.gfa) 
- [ ] Add to pan-gene set 
- [ ] Load relevant mine 
- [ ] Add BLAST targets 
- [ ] Incorporate into GCV 
- [ ] Update the jekyll collections listing 
- [ ] Update browser configs
- [ ] run BUSCO

**Comment by StevenCannon-USDA** [comment]
Closing this, as I inadvertently added a new issue for this task (and partly filled out the task list). See https://github.com/legumeinfo/datastore-issues/issues/194
