### ISSUE TITLE
Phaseolus vulgaris cv OAC Rex genome

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/datastore-issues#183]
### Main steps for adding new genome and annotation collections

# Genus/species/collection names: 
- Phaseolus/vulgaris/genomes/OACRex.gnm2.NXJW 
- [no corresponding annotation available as of October 2023. I have commented out the annotation-specific tasks for now.]

- [x] Add collection(s) to the Data Store
- [x] Validate the README(s)
- [x] Update about_this_collection.yml

- [x] Add BLAST targets 

- [x] run BUSCO

**Comment by adf-ncgr** [comment]
BUSCO and BLAST added (the latter to https://phaseolus.legumeinfo.org/tools/sequenceserver/). Will close it for now, could be reopened if annotation matures.
