### ISSUE TITLE
QTLs with markers on different chromosomes

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#188]
We've got some True Funkiness here. I edited my `lis-populate-qtl-genes` post-processor to check that a QTL's associated markers, which are used in that routine to find genes spanned by them on the chromosome, are on a single chromosome. Lo and behold, that is not the case. Here's an example:
```
[corePostProcess] QTL Cerinza_x_G24404.qtl.Blair_Iriarte_2006:df2.1 has markers on different chromosomes: 
[corePostProcess] phavu.G19833.gnm1.BM143       BM143   phavu.G19833.gnm1.Chr07
[corePostProcess] phavu.G19833.gnm1.BM142       BM142   phavu.G19833.gnm1.Chr05
```
Here's the qtlmrk.tsv file:
```
[shokin@lupini-mines qtl]$ zgrep df2.1 Cerinza_x_G24404.qtl.Blair_Iriarte_2006/phavu.Cerinza_x_G24404.qtl.Blair_Iriarte_2006.qtlmrk.tsv.gz 
df2.1	Days to flowering	Cerinza_x_G24404.Blair_Iriarte_2006	BM142	nearest
df2.1	Days to flowering	Cerinza_x_G24404.Blair_Iriarte_2006	BM143	flanking
df2.1	Days to flowering	Cerinza_x_G24404.Blair_Iriarte_2006	BMd3	flanking
```

Sure enough, BM142 and BM143 are on different chromosomes (BMd3 doesn't appear in our marker sets):

**phavu.G19833.gnm1.mrk.Blair_Pedraza_2003.gff3.gz:**
```
phavu.G19833.gnm1.Chr05	LIS	genetic_marker	32662546	32662727	.	+	.	ID=phavu.G19833.gnm1.BM142;Name=BM142
phavu.G19833.gnm1.Chr07	LIS	genetic_marker	14089633	14089710	.	+	.	ID=phavu.G19833.gnm1.BM143;Name=BM143
```
**phavu.G19833.gnm1.mrk.Gaitán-Solís_Duque_2002.gff3.gz**
```
phavu.G19833.gnm1.Chr05	Gaitan-Solis_Duque_2002	genetic_marker	32662546	32662727	.	+	.	ID=phavu.G19833.gnm1.BM142;Name=BM142
phavu.G19833.gnm1.Chr07	Gaitan-Solis_Duque_2002	genetic_marker	14089633	14089710	.	+	.	ID=phavu.G19833.gnm1.BM143;Name=BM143
```
Obviously I can just skip QTLs that fall into this category, but it strikes me as being very odd that 10 QTLs in this study are associated with markers on multiple chromosomes.

Any explanation for this? I'm guessing it's widespread, so I'll just issue a warning and ignore such QTLs. I presume those markers were thought to be on the same linkage group when they did the experiment. Maybe we mapped them to the genome?

**Comment by StevenCannon-USDA** [comment]
I note that these are all relatively old papers (2002 - 2006). They would all have used markers that could be assayed by older methods (e.g. Blair, Iriarte 2006: "genotyped with microsatellite, SCAR, and phaseolin markers").

My suspicion/bet: that some of these markers make poor sequence-based markers; that is: that some have matches to several locations, or the sequence marker isn't actually a proper match to the original old-school marker.

Your approach of "just issuing a warning and ignoring such QTLs" sounds pragmatic and appropriate to me.

**Comment by sammyjava** [comment]
Sounds good, that's what I've coded in the new post-processor so I'll close this issue.

**Comment by sammyjava** [comment]
(It'll be interesting to count how often this happens on GlycineMine, which has 313 QTL studies.)
