### ISSUE TITLE
Change publication DOI for Wm82.gnm2.div.Torkamaneh_Laroche_2019

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/datastore-issues#201]
The paper DOI for Wm82.gnm2.div.Torkamaneh_Laroche_2019 is wrong.  They did write a paper about it so we need to change the paper DOI to: /10.1111/pbi.13466 @jd-campbell @StevenCannon-USDA @maxglycine

**Comment by StevenCannon-USDA** [comment]
I have made this change in the Data Store. The change should show up on the websites when we update the datastore-metadata submodule.
