### ISSUE TITLE
Zhang_Jiang_2020 citation needs to change

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/datastore-issues#204]
It seems that Zhang_Jiang_2020 has published a paper about the 1500 soybean strains:

https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-022-08326-w

Zhang, H., Jiang, H., Hu, Z. et al. Development of a versatile resource for post-genomic research through consolidating and characterizing 1500 diverse wild and cultivated soybean genomes. BMC Genomics 23, 250 (2022). https://doi.org/10.1186/s12864-022-08326-w 
@jd-campbell @StevenCannon-USDA

**Comment by StevenCannon-USDA** [comment]
I have updated the README. I am not sure when the change will show up in the Mine. 

For the record, here are the steps involved in updating the metadata and getting that change reflected at the GitHub repository:
```
# ssh to peanutbase-stage.usda.iastate.edu

# cd to the collection to be edited and edit README.Wm82.gnm2.div.Zhang_Jiang_2020.yml
cd /usr/local/www/data/v2/Glycine/max/diversity/Wm82.gnm2.div.Zhang_Jiang_2020

# validate the README
  validate.sh readme README.Wm82.gnm2.div.Zhang_Jiang_2020.yml
  
# Recalculate the md5sum (calling the script on the containing collection folder)
  cd /usr/local/www/data/v2/Glycine/max/diversity
  /usr/local/www/data/datastore-specifications/scripts/mdsum-folder.bash Wm82.gnm2.div.Zhang_Jiang_2020
  
# Update the GitHub repo
  git add Wm82.gnm2.div.Zhang_Jiang_2020/CHECKSUM.Wm82.gnm2.div.Zhang_Jiang_2020.md5
  git add Wm82.gnm2.div.Zhang_Jiang_2020/README.Wm82.gnm2.div.Zhang_Jiang_2020.yml
  git commit -m "Update Zhang_Jiang_2020 citation"
  git push
  ```

**Comment by StevenCannon-USDA** [comment]
Closing, as this update has been made.
