### ISSUE TITLE
phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014 uses inconsistent sample identifiers

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#210]
loader reported this issue:
`[convertFile] ## INVALID: phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.obo.tsv.gz contains a sample that is not present in samples.tsv file.
`
looks like the obo file is using SRR ids, possible a holdover from previous analysis of this same dataset. Let's use the SRX that nf-core uses as primary.

**Comment by adf-ncgr** [comment]
@el239 let me know when you have this handled, I think I have all the other expression datasets loaded now but this one.

**Comment by el239** [comment]
That was indeed the case, should be corrected now.
