### ISSUE TITLE
Wm82_ISU01.gnm2.mrk needs to be renamed 

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/datastore-issues#214]
I found a directory and files named Wm82_ISU01.gnm2.mrk.

These files need to be renamed to Wm82.gnm6

https://data.legumeinfo.org/Glycine/max/markers/

**Comment by StevenCannon-USDA** [comment]
I can take that.
That collection is referred to at `tools/translate/index.html`, `collections/`, and probably JBrowse, so we'll need to update jekyll-soybase.

**Comment by StevenCannon-USDA** [comment]
For review in https://github.com/soybase/jekyll-soybase/pull/178
