### ISSUE TITLE
 glyma.Wm82_IGA1008.gnm1.ann1 gene_models_main is incomplete

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#25]
Caused by: java.lang.RuntimeException: Cannot determine primaryIdentifier from GFF record:
<GFF3Record: sequenceID: glyma.Wm82_IGA1008.gnm1.chr01 source: transdecoder type: three_prime_UTR start: 41092 end: 41325 score: null strand: - phase: null attributes: {Parent=[glyma.Wm82_IGA1008.gnm1.ann1.SoyW82_01R003065.1]}>

**Comment by adf-ncgr** [comment]
fixed by running /usr/local/www/data/about_the_data_store/scripts/add_IDs_to_gff_features.pl
(+ bgzip + tabix + update CHANGES + md5sum)
