### ISSUE TITLE
glyma.Wm82.gnm2.ann2.BG1Q.protein.faa has duplicate entries

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#28]
Caused by: org.intermine.objectstore.ObjectStoreException: Duplicate objects found for pk org.intermine.model.bio.Protein.key_primaryidentifier: Protein [annotationVersion="ann2", assemblyVersion="gnm2", description=null, geneFamily=null, geneFamilyScore=null, geneFamilyScoreMeaning=null, id=7342, length=460, md5checksum=null, molecularWeight=null, name=null, organism=0, panGeneSet=null, phylonode=null, primaryAccession=null, primaryIdentifier="glyma.Wm82.gnm2.ann2.PHYTASE.1", secondaryIdentifier="PHYTASE.1", sequence=7341, strain=1, symbol=null]

**Comment by adf-ncgr** [comment]
I have no idea how this protein file was generated, but this is an NCBI annotation that I think needs more attention if we're going to consider it to be conformant to our standards. For example, the PHYTASE gene representation puts full yuck on the Name/gene attributes and the ID is left presumably as it came in: 
glyma.Wm82.gnm2.ann2.Gm14   BestRefSeq%2CGnomon gene    1781016 1783960 .   +   .   ID=gene40103;Dbxref=GeneID:100787977;Name=glyma.Wm82.gnm2.ann2.PHYTASE;description=purple acid phosphatase 18-like;gbkey=Gene;gene=glyma.Wm82.gnm2.ann2.PHYTASE;gene_biotype=protein_coding

So I'm declaring this WONTFIX until we decide more generally how we want to deal with pulling NCBI annotations into the datastore.

**Comment by sammyjava** [comment]
So WONTFIX I presume means DONTLOAD. I'll delete Wm82.gnm2 from my local copy of the DS.

**Comment by adf-ncgr** [comment]
yeah, DONTLOAD is fine with me for the time being.

**Comment by adf-ncgr** [comment]
NB. Don't delete Wm82.gnm2  or  Wm82.gnm2.ann1 they should both be fine.
 Wm82.gnm2.ann2 is the genbank version of annotations on Wm82.gnm2 and it doesn't really supercede Wm82.gnm2.ann1 
as far as I know

**Comment by sammyjava** [comment]
Yeah I got that, just ann2 gets punted into the stands.

**Comment by cann0010** [comment]
I don't know whether it will be of interest at this point, but I have generated a GFF for glyma.Wm82.gnm2.ann2 that I think follows our conventions. I did it by mapping the ds_primaryTranscript onto the genome using gmap and then doing a bit of post-processing on the IDs - so it is not a full-Monty GFF (it is missing UTRs), but at least the IDs and Names correspond with the CDS fasta. I'll mention that my purpose was for calculating a new pan-gene set. I figure the RefSeq models ought to be included - both for their opinion regarding gene content, and to enable look-ups between the RefSeq and other annotations.

**Comment by adf-ncgr** [comment]
Hi Steven-
it's of interest but a bit confusing to me. I think the original issue here is that the NCBI files don't use ID and Name in the way we are used to, which leads to non-uniqueness in the fasta headers when "standard tools" (e.g. gffread) are used to derive them. I'm not entirely sure how the cds and protein files were created but you can see the issues with them like this:
[adf@lis /usr/local/www/data/v2/Glycine/max/annotations/Wm82.gnm2.ann2.BG1Q]$ zgrep '^>' glyma.Wm82.gnm2.ann2.BG1Q.cds.fna.gz | sort | uniq -c | sort -nr | more
  50 >glyma.Wm82.gnm2.ann2.GMSWEET50.1
  49 >glyma.Wm82.gnm2.ann2.N-24.1
  44 >glyma.Wm82.gnm2.ann2.LOC102668814.1
  30 >glyma.Wm82.gnm2.ann2.LOC102661462.1
  30 >glyma.Wm82.gnm2.ann2.LOC100807255.1
  30 >glyma.Wm82.gnm2.ann2.LOC100787792.1
  26 >glyma.Wm82.gnm2.ann2.LOC100811424.1
  25 >glyma.Wm82.gnm2.ann2.LOC100789712.1
  22 >glyma.Wm82.gnm2.ann2.LOC100790647.1
  21 >glyma.Wm82.gnm2.ann2.LOC100804053.1
...

[adf@lis /usr/local/www/data/v2/Glycine/max/annotations/Wm82.gnm2.ann2.BG1Q]$ zgrep '^>' glyma.Wm82.gnm2.ann2.BG1Q.protein.faa.gz | awk '{print $1}' | sort | uniq -c | sort -nr | more
  50 >glyma.Wm82.gnm2.ann2.GMSWEET50.1
  49 >glyma.Wm82.gnm2.ann2.N-24.1
  44 >glyma.Wm82.gnm2.ann2.LOC102668814.1
  30 >glyma.Wm82.gnm2.ann2.LOC102661462.1
  30 >glyma.Wm82.gnm2.ann2.LOC100807255.1
  30 >glyma.Wm82.gnm2.ann2.LOC100787792.1
  26 >glyma.Wm82.gnm2.ann2.LOC100811424.1
  25 >glyma.Wm82.gnm2.ann2.LOC100789712.1
  22 >glyma.Wm82.gnm2.ann2.LOC100790647.1
  21 >glyma.Wm82.gnm2.ann2.LOC100804053.1
...

I don't think mapping these back to the genome is the way to go if we want them in the pangene set. I think we ought to convert the gff to following our conventions (which is more than just tacking on a prefix to existing IDs) and then use the coordinates for the genes/transcripts already supplies there. N'est-ce pas?

**Comment by adf-ncgr** [comment]
PS. I see that the primaryTranscript versions of these files don't have the duplicate header id problem, but I'm not sure whether that invalidates the point I was trying to make

**Comment by cann0010** [comment]
I don't disagree that the gene_models_main.gff3 should be fixed ... but I couldn't see how to do it in the time available to me. I don't recall all the issues, but I think they were multiple and non-trivial. So I derived a passable gff that corresponds with cds_primaryTranscript.

**Comment by adf-ncgr** [comment]
yes, I think it will definitely be a bit complicated, but likely whatever we figure out for soybean will apply to other genomes that NCBI has independently annotated so probably worth doing (by someone with more time!). Anyway, I was more or less just trying to ensure the intent is not to replace gene_models_main with the alt version (which as you note has some lack of Monty).
