### ISSUE TITLE
Cajanus_cajan genome/annotation files

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#3]
@jd-campbell commented on [Thu Oct 12 2017](https://github.com/LegumeFederation/datastore/issues/14)

**DUE: November 24th, 2017**
Cajanus_cajan (pigeonpea) genome/annotation files need to be worked on. 

- [x] 1. Genome directory and annotation directory need a key 
- [x] 2. Metadata files need to be started (paper reference? people assisted w/ project so I can list)
- [x] 3. Rename files to data store standards
- [x] 4. Transfer to public

---

@adf-ncgr commented on [Thu Oct 12 2017](https://github.com/LegumeFederation/datastore/issues/14#issuecomment-336249706)

Hi Jacqueline-
nice use of tasklist notation- I think you've become a githubmaster already.

one thing I'd like to discuss before we go too far with pigeonpea; there exists a DOI for the genome+annotation 
http://dx.doi.org/10.5524/100028
resolving to
http://gigadb.org/dataset/100028

I think what is in the datastore corresponds to:
http://www.ceg.icrisat.org/gt-bt/iipg/genomedata.zip
(linked from http://www.ceg.icrisat.org/gt-bt/iipg/Genome_Manuscript.html which is actually used in the manuscript)
this has both the subfolders 2.2 gene_total and 2.3 gene_TEs_excluded (as well as
the others); I think when chado was loaded we probably took "gene_total" whereas the browser team probably loaded the gffs in 2.3_gene_TEs_excluded as separate tracks. 
2.2_gene_total/Pigeonpea_gene.gff:48680
2.3_gene_TEs_excluded/Pigeonpea.gff.TE.gff:8609
2.3_gene_TEs_excluded/Pigeonpea.gff.filterTE.gff:40071

using the filtered version seems like the appropriate thing to do, but explaining the provenance of all this seems a bit challenging. anyway, just wanted to get this on your radar as what I think we meant in terms of "rationalizing" the chado-datastore representations in that agenda item.

---

@adf-ncgr commented on [Fri Nov 03 2017](https://github.com/LegumeFederation/datastore/issues/14#issuecomment-341820078)

OK, in order to help get this process moving (and also to facilitate @sdash-github work to get a cajca gene atlas in place before my ICRISAT trip), I have assigned "keys" and created an AHRD-ified version of 2.3_gene_TEs_excluded/Pigeonpea.gff.filterTE.gff following the current standards for naming (ie with datastore-derived prefixes for unique naming) and following the proposal outlined in RFO #17. In the absence of Objections early next week, I will press forward with retrofitting our chado to reflect the contents of this file.

**Comment by jd-campbell** [comment]
**Note:** Went to original source (http://dx.doi.org/10.5524/100028) and found that the genome file already downloaded by Steven (Pigeonpea.scafSeq.LG.fa) was different from the original source (PigeonPea.scafSeq.LG_V5.0.fa). (ie, different checksum numbers). Compared number of Chr and scaffolds, file size - no difference.  Found that the file download by Steven had a Chr name of >Cc03 and the original file had a Chr name of >CcLG03.  I will keep both files but will continue working with the file downloaded from the original source (PigeonPea.scafSeq.LG_V5.0.fa).

**Comment by adf-ncgr** [comment]
thanks @jd-campbell : FWIW, I think (though @cann0010 should correct me if my inference is wrong) that "the genome file already downloaded by Steven (Pigeonpea.scafSeq.LG.fa)" is from 
http://www.ceg.icrisat.org/gt-bt/iipg/genomedata.zip
but also has been name-modified to suit browser conventions. I believe I checked this a few weeks ago by redownloading http://www.ceg.icrisat.org/gt-bt/iipg/genomedata.zip and verifying that the original naming was indeed of the "CcLG03" flavor (which is what I've retained in chado, modulo the traditional prefixing scheme). I'm truly sorry this is all so confusing. My hope is that someday we will have an approach to "onboarding other people's genomes" that we are all happy(ish) with and all clear(ish) about what we've agreed to as the approach! Tomorrow's datastore contributors will thank you for the pain you now endure...

**Comment by cann0010** [comment]
I think I am to blame for the original download and renaming. I do recall really not liking pseudomolecule names of the form "CcLG03" - because pseudomolecules are not linkage groups.
I agree that the genome version name in this case should be grandfathered-in.
