### ISSUE TITLE
CDCFrontier.gnm1.ann1.nRhs and ICC4958.gnm2.ann1.LCVX lack transcript FASTAs

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#33]
Since the vast majority of annotation collections contain transcript FASTAs, I'm entering this as an issue. If transcripts do not and will never exist, please delete this issue.

**Comment by adf-ncgr** [comment]
fixed using gffread to derive. in case of CDCFrontier.gnm1.ann1.nRhs cds and transcript files are equivalent but better to be consistent than parsimonious I guess.
