### ISSUE TITLE
cicar.ICC4958.gnm2.ann1.LCVX.gene_models_main.gff3 has CDS outside of gene range/out of order

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#45]
I don't get why this is popping up again, I thought you'd fixed this and others.
```
cicar.ICC4958.gnm2.contig63091	cicar.ICC4958.gnm2.ann1	CDS	395	547	.	+	1	ID=cicar.ICC4958.gnm2.ann1.Ca_24095.1.3;Parent=cicar.ICC4958.gnm2.ann1.Ca_24095.1
cicar.ICC4958.gnm2.contig63091	cicar.ICC4958.gnm2.ann1	gene	396	547	.	+	.	ID=cicar.ICC4958.gnm2.ann1.Ca_24095;Name=cicar.ICC4958.Ca_24095;Note=Unknown protein
cicar.ICC4958.gnm2.contig63091	cicar.ICC4958.gnm2.ann1	mRNA	396	547	.	+	.	ID=cicar.ICC4958.gnm2.ann1.Ca_24095.1;Parent=cicar.ICC4958.gnm2.ann1.Ca_24095;Name=cicar.ICC4958.Ca_24095.1
cicar.ICC4958.gnm2.contig63091	cicar.ICC4958.gnm2.ann1	exon	396	547	.	+	.	ID=cicar.ICC4958.gnm2.ann1.Ca_24095.1.1;Parent=cicar.ICC4958.gnm2.ann1.Ca_24095.1
```

**Comment by adf-ncgr** [comment]
It does look like I thought I had fixed it in #34. will have to have a closer look.

**Comment by adf-ncgr** [comment]
seems like this one was anomalous with respect to the pattern I had inferred, apparently it started 2bp before the gene initially and I only bumped things up by 1bp. probably I can apply the same fix once more, once I figure out exactly what I had done previously (thanks past adf for thinking "exact commands used to effect the change are not provided, but the diffs are provided in the file: changes_to_CDS_for_issue_34" would suffice)

**Comment by adf-ncgr** [comment]
this is re-fixed. seems that one was the only one needing the extra bp bump.
