### ISSUE TITLE
Duplicate Name value in lupal.Amiga.gnm1.ann1.3GKS.gene_models_main.gff3

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#49]
Since Name trumps ID when present, for forming primaryIdentifier, Name cannot be duplicated.
```
$ grep trnK-UUU_tRNA /data/v2/Lupinus/albus/annotations/Amiga.gnm1.ann1.3GKS/lupal.Amiga.gnm1.ann1.3GKS.gene_models_main.gff3
lupal.Amiga.gnm1.Lalb_chloroplast_genome	Geneious	tRNA	1705	1739	.	-	.	ID=lupal.Amiga.gnm1.ann1.trnK-UUU_tRNA_1;Parent=lupal.Amiga.gnm1.ann1.trnK-UUU_gene_1;Name=lupal.trnK-UUU_tRNA;gene=trnK-UUU;product=tRNA-Lys;note=anticodon:UUU;transcription=GGGTTGCTAACTCAACGGTAGAGTACTCGGCTTTTAACCGACTAGTTCCGGGTTCGAGTCCCGGGCAACCCA;ncbi_feature_key=tRNA;ncbi_join_type=join;transferred_From=KJ468099;transferred_Similarity=100.00%25
lupal.Amiga.gnm1.Lalb_chloroplast_genome	Geneious	tRNA	4367	4403	.	-	.	ID=lupal.Amiga.gnm1.ann1.trnK-UUU_tRNA_2;Parent=lupal.Amiga.gnm1.ann1.trnK-UUU_gene_1;Name=lupal.trnK-UUU_tRNA;gene=trnK-UUU;product=tRNA-Lys;note=anticodon:UUU;transcription=GGGTTGCTAACTCAACGGTAGAGTACTCGGCTTTTAACCGACTAGTTCCGGGTTCGAGTCCCGGGCAACCCA;ncbi_feature_key=tRNA;ncbi_join_type=join;transferred_From=KJ468099;transferred_Similarity=100.00%25
```

**Comment by adf-ncgr** [comment]
I don't see duplicated Name attributes in your example or in the file in the datastore. Is some other attribute being treated like a Name?

**Comment by sammyjava** [comment]
Both those records have Name=lupal.trnK-UUU_tRNA. Remember, Name trumps ID in the GFF loader.

**Comment by adf-ncgr** [comment]
Oh, I thought you meant the same record had multiple Name attributes like the other recent one. Will have to think about what's best here.

**Comment by sammyjava** [comment]
One option is to just drop Name since there are distinct ID values.

**Comment by sammyjava** [comment]
Although that's inconsistent with the rest of them. I'd just suck the Name from the ID (and yank the gensp in front, I end up doing that, anyway):
```
lupal.Amiga.gnm1.Lalb_chloroplast_genome	Geneious	tRNA	1705	1739	.	-	.	ID=lupal.Amiga.gnm1.ann1.trnK-UUU_tRNA_1;Parent=lupal.Amiga.gnm1.ann1.trnK-UUU_gene_1;Name=trnK-UUU_tRNA_1;gene=trnK-UUU;product=tRNA-Lys;note=anticodon:UUU;transcription=GGGTTGCTAACTCAACGGTAGAGTACTCGGCTTTTAACCGACTAGTTCCGGGTTCGAGTCCCGGGCAACCCA;ncbi_feature_key=tRNA;ncbi_join_type=join;transferred_From=KJ468099;transferred_Similarity=100.00%25
lupal.Amiga.gnm1.Lalb_chloroplast_genome	Geneious	tRNA	4367	4403	.	-	.	ID=lupal.Amiga.gnm1.ann1.trnK-UUU_tRNA_2;Parent=lupal.Amiga.gnm1.ann1.trnK-UUU_gene_1;Name=trnK-UUU_tRNA_2;gene=trnK-UUU;product=tRNA-Lys;note=anticodon:UUU;transcription=GGGTTGCTAACTCAACGGTAGAGTACTCGGCTTTTAACCGACTAGTTCCGGGTTCGAGTCCCGGGCAACCCA;ncbi_feature_key=tRNA;ncbi_join_type=join;transferred_From=KJ468099;transferred_Similarity=100.00%25
```

**Comment by adf-ncgr** [comment]
It looks like there are a lot of cases where genes have the same name as their transcript children (seemingly always for non-coding RNA types they aren't adding an isoform .1); I guess in the past we have decreed that mRNA should have .1 suffixes so probably this one should follow suit.

**Comment by adf-ncgr** [comment]
BTW, the version of the gff3 that's in the datastore has the lupal. prefix on the Names. Have you been stripping these off the others? I think there was an issue about this where you said you would.

**Comment by sammyjava** [comment]
Yeah, I strip them off before loading and hopefully update the files at Iowa State after I've promoted the mine. Which will soon be more automated with the Automated ISU Datastore Refresher (R).

**Comment by adf-ncgr** [comment]
fixed with script adding suffixes to Names seen previously. I guess it will make things work although I believe the fasta files derived from these use the IDs and these are not necessarily congruent (in fact I think non-congruence of Names and IDs may have been true before I made the fix).
