### ISSUE TITLE
lotja.MG20.gnm3.ann1.WF9B.gene_models_main.gff3 has duplicate Name entries

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#52]
You just fixed the CDS positioning but this has duplicate Name entries as well. I'd recommend writing a checker for this situation since it seems to be coming up an awful lot.
```
lotja.MG20.gnm3.Lj0	protein_coding	gene	159887799	159890585	.	+	.	ID=lotja.MG20.gnm3.ann1.Lj0g3v0306419;Name=known_Npl
lotja.MG20.gnm3.Lj0	protein_coding	mRNA	159887799	159890585	.	+	.	ID=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419;coverage=100.0;identity=98.3
lotja.MG20.gnm3.Lj0	protein_coding	exon	159887799	159887899	100	+	.	ID=known_Npl.mrna1.exon1;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 1 101 +
lotja.MG20.gnm3.Lj0	protein_coding	exon	159888933	159889650	97	+	.	ID=known_Npl.mrna1.exon2;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 102 839 +
lotja.MG20.gnm3.Lj0	protein_coding	CDS	159889529	159889650	100	+	0	ID=known_Npl.mrna1.cds1;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 718 839 +
lotja.MG20.gnm3.Lj0	protein_coding	exon	159889922	159890060	100	+	.	ID=known_Npl.mrna1.exon3;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 840 978 +
lotja.MG20.gnm3.Lj0	protein_coding	CDS	159889922	159890060	100	+	2	ID=known_Npl.mrna1.cds2;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 840 978 +
lotja.MG20.gnm3.Lj0	protein_coding	exon	159890361	159890585	100	+	.	ID=known_Npl.mrna1.exon4;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 979 1203 +
lotja.MG20.gnm3.Lj0	protein_coding	CDS	159890361	159890585	100	+	0	ID=known_Npl.mrna1.cds3;Name=known_Npl;Parent=lotja.MG20.gnm3.ann1.Lj0g3v0306419.1;Target=known_Npl 979 1203 +
```

**Comment by adf-ncgr** [comment]
yeah, unfortunately Names were never meant to be unique identifiers in gff, they were meant to be browser display labels- so it's probably not surprising it happens. I think I understand the logic you've implemented but I suspect other readers of these files play by different rules and I'm not altogether clear on what the implications of changes I make on these things might be. Pretty sure no lives will be lost, though.

**Comment by sammyjava** [comment]
We have to specify GFFs more than the GFF spec, otherwise, we cannot build the mines. It was a choice between forcing ID to have an LIS-compliant value, which is also beyond the GFF spec, or requiring unique Name. There was no other choice, and given the fact that I could build primaryIdentifier from the Name attribute in GFFs that had IDs like "1", "2", "3" we chose to use Name as the source. That could be changed of course, with the requirement that all LIS GFFs have unique meaningful ID values.

**Comment by adf-ncgr** [comment]
the gff spec working group advocated for introducing a new attribute for meaningful-outside-the-file-unique-ids. Maybe someday we'll adopt that instead. after all your new students have graduated college somewhere...

**Comment by adf-ncgr** [comment]
fixed with /usr/local/www/data/about_the_data_store/scripts/ensure_name_uniqueness.pl
