### ISSUE TITLE
medtr.HM004.gnm1.ann1.2XTB.gene_models_main.gff3 lacks ID and Name for exons/CDSes

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#56]
This isn't necessarily ready for mine time, but I wanted to use this GFF to test my new tweak to the ID/Name logic for primaryIdentifier/secondaryIdentifier. But it's unloadable.

**Comment by adf-ncgr** [comment]
OK I will IDify it, soon.

**Comment by adf-ncgr** [comment]
The version in intermine loading space (ie under /erdos/legumeinfo) now has IDs for exons and CDSs. Not sure this will make it loadable, but you can give it a try. This same problem will probably recur for all the others, but I'm considering this just a version to enable code testing (and I'm not sure whether I'll leave the gene/transcript names as they are in this version)

**Comment by sammyjava** [comment]
Thank you, sir. Yes, just for testing the loader tweak, and it does now load. Here's some pages to ponder:

https://dev.lis.ncgr.org/medicmine/report.do?id=2000006
https://dev.lis.ncgr.org/medicmine/report.do?id=2015214
https://dev.lis.ncgr.org/medicmine/report.do?id=2015209
https://dev.lis.ncgr.org/medicmine/report.do?id=9001803
