### ISSUE TITLE
glyso.F_IGA1003.gnm1.ann1.G61B.gene_models_main.gff3 lacks IDs/Names

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#58]
Caused by: java.lang.RuntimeException: Cannot determine primaryIdentifier from GFF record:
<GFF3Record: sequenceID: glyso.F_IGA1003.gnm1.chr01 source: maker type: CDS start: 14397 end: 14565 score: null strand: - phase: 1 attributes: {Parent=[glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_01R003185.1]}>

**Comment by adf-ncgr** [comment]
fixed (I hope) by application of /usr/local/www/data/about_the_data_store/scripts/add_IDs_to_gff_features.pl
