### ISSUE TITLE
glyso.F_IGA1003.gnm1.ann1.G61B.gene_models_main.gff3: gene on scaffold while children on chromosome

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#59]
This breaks sorting (fortunately).
```
glyso.F_IGA1003.gnm1.chr11      maker   mRNA    6941    10361   .       +       .       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200;Name=SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.chr11      maker   five_prime_UTR  6941    7294    .       +       .       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1-five_prime_UTR-1;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.chr11      maker   CDS     7295    7424    .       +       0       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1-CDS-1;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.chr11      maker   CDS     7701    7885    .       +       2       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1-CDS-2;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.chr11      maker   CDS     9162    9362    .       +       0       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1-CDS-3;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.chr11      maker   CDS     9695    9856    .       +       0       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1-CDS-4;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.chr11      maker   CDS     9972    10331   .       +       0       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1-CDS-5;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.chr11      maker   three_prime_UTR 10332   10361   .       +       .       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1-three_prime_UTR-1;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200.1
glyso.F_IGA1003.gnm1.unanchor105        maker   gene    6941    10361   .       +       .       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200;Name=SoyGsojaF_11G000200;Note=nucleotide/sugar transporter family protein
```

**Comment by adf-ncgr** [comment]
That's messed up. Why is the gene on an unanchored scaffold and the rest on chr11 ? while looking at this I also noticed an apparently orthogonal (but possibly related) peculiarity:
glyso.F_IGA1003.gnm1.chr102 maker   gene    1273    18428   .   +   .   ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_UR057928;Name=SoyGsojaF_UR057928;Note=protein PLASTID MOVEMENT IMPAIRED 2
which seems to be part of a small set of "chr" that don't look very chromosome-like:
   1 glyso.F_IGA1003.gnm1.chr208
   1 glyso.F_IGA1003.gnm1.chr189
   1 glyso.F_IGA1003.gnm1.chr131
   1 glyso.F_IGA1003.gnm1.chr115
   1 glyso.F_IGA1003.gnm1.chr102

@cann0010 looking at the CHANGES file it looks like there was some funky perl used to deal with funkier original files still extant in /usr/local/www/data/private/Glycine/soja/F_IGA1003.gnm1.ann1.G61B/IGA1003.gene.gff that lead me to believe without careful analysis that some of the perl funk did not eliminate the funky but may have in some cases morphed it though not immediately obvious to me how we would have produced an "unanchored" gene:
glyso.F_IGA1003.gnm1.unanchor105	maker	gene	6941	10361	.	+.	ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_11G000200;Name=SoyGsojaF_11G000200;Note=nucleotide/sugar transporter family protein 
from implicit children on chr11. 

going to reassign it to you, as the reward for doing hard but funky work is more funky work (hopefully not as hard)

**Comment by sammyjava** [comment]
WHO got the funk? YOU got the funk!

**Comment by cann0010** [comment]
OK. That's ungodly. I will smite that gene.

**Comment by cann0010** [comment]
I should mention: I'll be on the road today through Sunday. Probably won't get to this until next week.

**Comment by cann0010** [comment]
I have fixed at least the problems identified above. The issues affected only the GFF, as far as I can see. I ran it through AGAT, which added exon features. The two GFF files are:
glyso.F_IGA1003.gnm1.ann1.G61B.gene_models_exons.gff3.gz
glyso.F_IGA1003.gnm1.ann1.G61B.gene_models_main.gff3.gz

**Comment by sammyjava** [comment]
It appears that your fix is incomplete:
```
[shokin@lis ~]$ zgrep glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226 v2/Glycine/soja/annotations/F_IGA1003.gnm1.ann1.G61B/glyso.F_IGA1003.gnm1.ann1.G61B.gene_models_main.gff3.gz
glyso.F_IGA1003.gnm1.chr12      GlimmerHMM      mRNA    2185    3262    .       -       .       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226.1;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226;Name=SoyGsojaF_12R050226.1
glyso.F_IGA1003.gnm1.chr12      GlimmerHMM      CDS     2185    2241    .       -       0       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226.1-CDS-1;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226.1
glyso.F_IGA1003.gnm1.chr12      GlimmerHMM      CDS     2318    2431    .       -       0       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226.1-CDS-2;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226.1
glyso.F_IGA1003.gnm1.chr12      GlimmerHMM      CDS     2864    3262    .       -       0       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226.1-CDS-3;Parent=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226.1
glyso.F_IGA1003.gnm1.unanchor115        GlimmerHMM      gene    2185    3262    .       -       .       ID=glyso.F_IGA1003.gnm1.ann1.SoyGsojaF_12R050226;Name=SoyGsojaF_12R050226;Note=ribonuclease P
```

**Comment by cann0010** [comment]
Ugh. Funkier than I realized. There are 35 such molecule-spanning gene models.
I'll probably get rid of all of those. That will require touching all of the annotation files. Probably a task for another day.
`cut -f1,9 glyso.F_IGA1003.gnm1.ann1.G61B.gene_models_main.gff3 | cut -f1 -d';' | 
  perl -pe 's/(SoyGsojaF_\w+\d+)\..+/$1/; s/ID=glyso.F_IGA1003.gnm1.ann1\.//' | 
  awk '{print $2 "\t" $1}' | sort | uniq -c | 
  awk '$2==prevgene {print prevline; print $0; prevgene=$2; prevline=$0} $2!=prevgene {prevgene=$2; prevline=$0}'
   4 SoyGsojaF_12R050226  glyso.F_IGA1003.gnm1.chr12
   1 SoyGsojaF_12R050226  glyso.F_IGA1003.gnm1.unanchor115
   4 SoyGsojaF_14R021151  glyso.F_IGA1003.gnm1.chr14
   1 SoyGsojaF_14R021151  glyso.F_IGA1003.gnm1.unanchor131
   2 SoyGsojaF_19R009129  glyso.F_IGA1003.gnm1.chr19
   1 SoyGsojaF_19R009129  glyso.F_IGA1003.gnm1.unanchor189
   1 SoyGsojaF_UR057537 glyso.F_IGA1003.gnm1.unanchor286
   5 SoyGsojaF_UR057537 glyso.F_IGA1003.gnm1.unanchor289
   1 SoyGsojaF_UR057771 glyso.F_IGA1003.gnm1.unanchor298
   2 SoyGsojaF_UR057771 glyso.F_IGA1003.gnm1.unanchor299
   1 SoyGsojaF_UR057820 glyso.F_IGA1003.gnm1.unanchor220
   3 SoyGsojaF_UR057820 glyso.F_IGA1003.gnm1.unanchor265
   1 SoyGsojaF_UR057823 glyso.F_IGA1003.gnm1.unanchor283
   8 SoyGsojaF_UR057823 glyso.F_IGA1003.gnm1.unanchor286
   1 SoyGsojaF_UR057833 glyso.F_IGA1003.gnm1.unanchor289
  11 SoyGsojaF_UR057833 glyso.F_IGA1003.gnm1.unanchor290
   1 SoyGsojaF_UR057848 glyso.F_IGA1003.gnm1.unanchor296
   2 SoyGsojaF_UR057848 glyso.F_IGA1003.gnm1.unanchor297
   1 SoyGsojaF_UR057864 glyso.F_IGA1003.gnm1.unanchor297
   2 SoyGsojaF_UR057864 glyso.F_IGA1003.gnm1.unanchor298
   1 SoyGsojaF_UR057877 glyso.F_IGA1003.gnm1.unanchor306
   2 SoyGsojaF_UR057877 glyso.F_IGA1003.gnm1.unanchor309
   1 SoyGsojaF_UR057881 glyso.F_IGA1003.gnm1.unanchor295
   4 SoyGsojaF_UR057881 glyso.F_IGA1003.gnm1.unanchor296
   1 SoyGsojaF_UR057885 glyso.F_IGA1003.gnm1.unanchor299
   3 SoyGsojaF_UR057885 glyso.F_IGA1003.gnm1.unanchor30
   1 SoyGsojaF_UR057889 glyso.F_IGA1003.gnm1.unanchor267
   2 SoyGsojaF_UR057889 glyso.F_IGA1003.gnm1.unanchor268
   1 SoyGsojaF_UR057890 glyso.F_IGA1003.gnm1.unanchor268
  11 SoyGsojaF_UR057890 glyso.F_IGA1003.gnm1.unanchor270
   1 SoyGsojaF_UR057892 glyso.F_IGA1003.gnm1.unanchor290
   3 SoyGsojaF_UR057892 glyso.F_IGA1003.gnm1.unanchor291
   1 SoyGsojaF_UR057894 glyso.F_IGA1003.gnm1.unanchor276
   5 SoyGsojaF_UR057894 glyso.F_IGA1003.gnm1.unanchor277
   1 SoyGsojaF_UR057896 glyso.F_IGA1003.gnm1.unanchor312
   3 SoyGsojaF_UR057896 glyso.F_IGA1003.gnm1.unanchor313
   1 SoyGsojaF_UR057897 glyso.F_IGA1003.gnm1.unanchor300
   4 SoyGsojaF_UR057897 glyso.F_IGA1003.gnm1.unanchor305
   1 SoyGsojaF_UR057899 glyso.F_IGA1003.gnm1.unanchor305
  10 SoyGsojaF_UR057899 glyso.F_IGA1003.gnm1.unanchor306
   1 SoyGsojaF_UR057900 glyso.F_IGA1003.gnm1.unanchor30
   2 SoyGsojaF_UR057900 glyso.F_IGA1003.gnm1.unanchor300
   1 SoyGsojaF_UR057911 glyso.F_IGA1003.gnm1.unanchor313
   2 SoyGsojaF_UR057911 glyso.F_IGA1003.gnm1.unanchor57
   1 SoyGsojaF_UR057913 glyso.F_IGA1003.gnm1.unanchor57
   3 SoyGsojaF_UR057913 glyso.F_IGA1003.gnm1.unanchor60
   1 SoyGsojaF_UR057915 glyso.F_IGA1003.gnm1.unanchor60
   2 SoyGsojaF_UR057915 glyso.F_IGA1003.gnm1.unanchor73
   1 SoyGsojaF_UR057927 glyso.F_IGA1003.gnm1.unanchor73
   2 SoyGsojaF_UR057927 glyso.F_IGA1003.gnm1.unanchor75
   1 SoyGsojaF_UR057931 glyso.F_IGA1003.gnm1.unanchor102
   7 SoyGsojaF_UR057931 glyso.F_IGA1003.gnm1.unanchor103
   1 SoyGsojaF_UR057935 glyso.F_IGA1003.gnm1.unanchor294
   2 SoyGsojaF_UR057935 glyso.F_IGA1003.gnm1.unanchor295
   1 SoyGsojaF_UR057939 glyso.F_IGA1003.gnm1.unanchor291
   2 SoyGsojaF_UR057939 glyso.F_IGA1003.gnm1.unanchor294
   1 SoyGsojaF_UR057942 glyso.F_IGA1003.gnm1.unanchor309
   4 SoyGsojaF_UR057942 glyso.F_IGA1003.gnm1.unanchor310
   1 SoyGsojaF_UR057945 glyso.F_IGA1003.gnm1.unanchor270
   8 SoyGsojaF_UR057945 glyso.F_IGA1003.gnm1.unanchor272
   1 SoyGsojaF_UR057946 glyso.F_IGA1003.gnm1.unanchor265
   3 SoyGsojaF_UR057946 glyso.F_IGA1003.gnm1.unanchor267
   1 SoyGsojaF_UR057949 glyso.F_IGA1003.gnm1.unanchor310
   2 SoyGsojaF_UR057949 glyso.F_IGA1003.gnm1.unanchor312
   1 SoyGsojaF_UR057951 glyso.F_IGA1003.gnm1.unanchor272
   3 SoyGsojaF_UR057951 glyso.F_IGA1003.gnm1.unanchor276
   1 SoyGsojaF_UR057960 glyso.F_IGA1003.gnm1.unanchor208
   6 SoyGsojaF_UR057960 glyso.F_IGA1003.gnm1.unanchor220
   1 SoyGsojaF_UR057961 glyso.F_IGA1003.gnm1.unanchor277
   5 SoyGsojaF_UR057961 glyso.F_IGA1003.gnm1.unanchor283
`

**Comment by cann0010** [comment]
OK. I've gotten rid of all 35 of those molecule-straddling genes, in all of the files.
Hoping that this takes care of it!

**Comment by sammyjava** [comment]
Looks good, mostly. I had to resort it and there was one gene Name that had a .1 at the end (which broke merging because I've already got Gene.name stored from other sources). But I can fix anything else that happens.
