### ISSUE TITLE
Specification of GENUS description files needs improvements, error corrections

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#60]
I'm writing a script to populate the genus-level content on the Jekyll site, and I see that the description files under GENUS are really inherited from the species-specific files and, as such, actually contain inaccuracies. For example:
**v2/Arachis/GENUS/about_this_collection/description_Arachis_sp.yml** Note 0.
```
---
organism.taxid: 3818       Note 1.
organism.genus: Arachis
organism.species: sp       Note 2.
organism.abbrev: arasp     Note 3.
organism.commonName: Arachis
organism.description: The genus Arachis contains approximately 69 species, distributed in South America east of the Andes, in the regions or Argentina, Bolivia, and Brazil. Krapovickas, A. & W.C. Gregory. 2006. Taxonomy of the genus Arachis (Leguminosae). Translated by D.E. Williams & C.E. Simpson. 
```
Note 0. Seems the file should be `v2/Arachis/GENUS/about_this_collection/description_Arachis.yml`
Note 1. This is the taxonomy ID for _hypogaea_; the ID for the genus is 3817. Is this simply a mistake?
Note 2. There should be no species in a genus description file.
Note 3. See above; obviously, this collides with _Arachis spatulensis_. Why do we need an abbreviation for genus only? The files all start with "mixed". The gensp notation is for species data, not genus-only data.

Can I fix these files so they actually contain appropriate and correct data for the genus alone? I'll be adding some attributes as well, possibly. (I plan to put services in a separate file.)

I'd really like the datastore to contain only data that are appropriate, which makes coding the site-population scripts more sensible and less error-prone. As well as other to-be-written consumers.

**Comment by cann0010** [comment]
Agree on the need to correct these files, and on the particular quibbles in your notes. I am all for your fixing them! I am also willing to do so if that is needed now (just a matter of juggling priorities).

**Comment by sammyjava** [comment]
No prob, just part of what I'm doing. I'll leave this open until I've redone all of them.

**Comment by sammyjava** [comment]
This is done and I put in a specification by example: https://github.com/legumeinfo/datastore-specifications/blob/main/Genus/GENUS/about_this_collection/description_Genus.yml
