### ISSUE TITLE
Add Name field to README specification

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#62]
Not a high priority, but it might be nice to restore the Name field to the README specification,
`Name: Otyama Cannon et al. 2021`
which existed for some of the GWAS datasets created under a previous version of the specification.

With the current specification, I use the Identifier field:
`identifier: USPeanutCore.gwas.Otyama_Kulkarni_2020`
which, though cryptic, is adequate - in ZZBrowse it appears as a hyperlink to the publication, with a summary when you mouse over it, so the details are at most one click away. I just think the Name looks cleaner.

**Comment by sammyjava** [comment]
What does the Name attribute refer to? We have the publication in the README already. Is Name something that we make up ourselves? Or is it the title of the publication or authors, as you suggest? Is it unique? If so, how do we enforce that? These are the considerations that went into the creation of an identifier like `USPeanutCore.gwas.Otyama_Kulkarni_2020`.

In these cases, I recommend looking at a relevant mine page:
https://mines.legumeinfo.org/peanutmine/report.do?id=51000003
and answering the question "what is missing here that we need?"

If there is something missing, let's add it. If it's something you can create off of these data, then create it. For example, you can strip ".gwas." out if the identifier and display `USPeanutCore - Otyama, Kulkarni, 2020` if that's desirable.

**Comment by svengato** [comment]
ZZBrowse already links to the publication, that should be sufficient.
