### ISSUE TITLE
Vigna/unguiculata/annotations/Xiabao_II.gnm1.ann1.4JFL/ lacks README

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#70]
Here's another README-lacking collection as discovered by running git status:

Vigna/unguiculata/annotations/Xiabao_II.gnm1.ann1.4JFL/

**Comment by adf-ncgr** [comment]
Vigna/unguiculata/genomes/Xiabao_II.gnm1.WDBP also lacks one. for no good reason, so will fix at some point

**Comment by sammyjava** [comment]
Still lacks an mrna FASTA. (But I loaded it otherwise.)

**Comment by sammyjava** [comment]
*ping* on the mRNA FASTA, @adf-ncgr

**Comment by adf-ncgr** [comment]
thanks, will have a look when datastore access returns

**Comment by nathanweeks** [comment]
The datastore should still be available?

**Comment by adf-ncgr** [comment]
it's availble via https://data.legumeinfo.org but I need to ssh to get access to the filesystem. let me know if that should be working again now

**Comment by sammyjava** [comment]
It's not gone down for me all day, I've been using it constantly. With an extant ssh session though.

**Comment by adf-ncgr** [comment]
extant session is the key; luckily, I do still have one among the myriad windows, so looking at it now.

**Comment by adf-ncgr** [comment]
OK, should be good to go
