### ISSUE TITLE
Inappropriate files in DS (or, make them appropriate with a specification)

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#71]
The datastore-metadata repo reports the following untracked files, based on the exclusions I placed in .gitignore. Please remove, or write a specification that makes them legitimate. I want to get to the point where there are no non-specified/validated metadata in the DS.
```
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Arachis/hypogaea/genomes/Shitouqi.gnm1.L4VP/.notes_Shitoqi.txt.swp
        Arachis/hypogaea/genomes/Tifrunner.gnm2.J5K5/README.HiC_assembly.json
        Cajanus/cajan/supplements/ICPL87119.bac1.GpKx/cajca.ICPL87119.bac1.GpKx.library_info.doc
        Cicer/arietinum/annotations/ICC4958.gnm2.ann1.LCVX/changes_to_CDS_for_issue_34
        Glycine/max/genomes/Wenfeng7_IGA1001.gnm1.L0QH/.README.L0QH.yml.swp
        Lotus/japonicus/annotations/MG20.gnm3.ann1.WF9B/changes_to_CDS_for_issue_43
        Lotus/japonicus/annotations/MG20.gnm3.ann1.WF9B/renaming_for_issue_52
        Lotus/japonicus/annotations/MG20.gnm3.ann1.WF9B/renaming_for_issue_52.diffs
        Lupinus/albus/annotations/Amiga.gnm1.ann1.3GKS/renaming_for_issue_43
        Lupinus/albus/annotations/Amiga.gnm1.ann1.3GKS/renaming_for_issue_43.diffs
        Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY/all.iprscan_raw
        Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY/error.log
        Medicago/truncatula/annotations/HM004.gnm1.ann1.2XTB/transcript2gene
        Medicago/truncatula/annotations/HM010.gnm1.ann1.WV9J/transcript2gene
        Medicago/truncatula/annotations/HM022.gnm1.ann1.6C8N/transcript2gene
        Medicago/truncatula/annotations/HM023.gnm1.ann1.WZN8/transcript2gene
        Medicago/truncatula/annotations/HM034.gnm1.ann1.YR6S/transcript2gene
        Medicago/truncatula/annotations/HM050.gnm1.ann1.GWRX/transcript2gene
        Medicago/truncatula/annotations/HM056.gnm1.ann1.CHP6/transcript2gene
        Medicago/truncatula/annotations/HM058.gnm1.ann1.LXPZ/transcript2gene
        Medicago/truncatula/annotations/HM060.gnm1.ann1.H41P/transcript2gene
        Medicago/truncatula/annotations/HM095.gnm1.ann1.55W4/transcript2gene
        Medicago/truncatula/annotations/HM125.gnm1.ann1.KY5W/transcript2gene
        Medicago/truncatula/annotations/HM129.gnm1.ann1.7FTD/transcript2gene
        Medicago/truncatula/annotations/HM185.gnm1.ann1.GB3D/transcript2gene
        Medicago/truncatula/annotations/HM324.gnm1.ann1.SQH2/transcript2gene
        Medicago/truncatula/annotations/jemalong_A17.gnm5.ann1_6.L2RX/.iprscan_updated
        Medicago/truncatula/annotations/jemalong_A17.gnm5.ann1_6.L2RX/all.iprscan_raw
        Medicago/truncatula/annotations/jemalong_A17.gnm5.ann1_6.L2RX/error.log
```

**Comment by sammyjava** [comment]
Note that we probably want to add useful scripts to GitHub, perhaps under a new repo `datastore-scripts`. There are a bunch of them sitting under /usr/local/www/data/about_the_data_store/scripts, but that currently contains 1330 directories, 10819 files
which seems highly inappropriate for a GitHub repo. It's more like an entire OS. Perhaps if I initialize a datastore-scripts repo folks can add them one by one AS USED, so we only have relevant stuff in there (and not executable binaries, which should be loaded from the OS packages or npm or wherever you get your podcasts.)

**Comment by sammyjava** [comment]
(I'll also note that any existing scripts that create READMEs need to be updated to produce valid READMEs.)

**Comment by cann0010** [comment]
I have addressed all of the files in the original comment (details below).
I blew away the transcript2gene and all.iprscan_raw files (these were shokin files; I guessed that they were intermediate/non-essential). I'll deal with the scripts in the new year, probably under a separate issue.
```
Arachis/hypogaea/genomes/Shitouqi.gnm1.L4VP/.notes_Shitoqi.txt.swp
  # Removed

Arachis/hypogaea/genomes/Tifrunner.gnm2.J5K5/README.HiC_assembly.json
  # Renamed: mv README.HiC_assembly.json original_readme_HiC_assembly_json.txt
  # this is a README from the Erez Lieberman Aiden lab (they did the HIC alignment). 
  # It is in json format for some reason. I have obscured that (changing the extension to .txt), since it doesn't need to be machine-readable.

Cajanus/cajan/supplements/ICPL87119.bac1.GpKx/cajca.ICPL87119.bac1.GpKx.library_info.doc
  # Translated from ancient Word .doc to plain text and deleted the .doc file.
  # This is legacy supplementary data, held at Doug Cook's the request.

Cicer/arietinum/annotations/ICC4958.gnm2.ann1.LCVX/changes_to_CDS_for_issue_34
  # Merged text from file "changes_to_CDS_for_issue_34" into the CHANGES file, and removed changes_to_CDS_for_issue_34.

Glycine/max/genomes/Wenfeng7_IGA1001.gnm1.L0QH/.README.L0QH.yml.swp
  # Removed the swap file.

Lotus/japonicus/annotations/MG20.gnm3.ann1.WF9B/changes_to_CDS_for_issue_43
  # Removed file changes_to_CDS_for_issue_43
  
Lotus/japonicus/annotations/MG20.gnm3.ann1.WF9B/renaming_for_issue_52
  # Merged text from file "renaming_for_issue_52" into the CHANGES file, and removed renaming_for_issue_52.
  # Removed file renaming_for_issue_52

Lotus/japonicus/annotations/MG20.gnm3.ann1.WF9B/renaming_for_issue_52.diffs
  # Removed file renaming_for_issue_52.diffs

Lupinus/albus/annotations/Amiga.gnm1.ann1.3GKS/renaming_for_issue_43
  # Merged text from renaming_for_issue_43 below, and removed file renaming_for_issue_43.

Lupinus/albus/annotations/Amiga.gnm1.ann1.3GKS/renaming_for_issue_43.diffs
  # Removed renaming_for_issue_43.diffs

Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY/all.iprscan_raw
  # Removed file

Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY/error.log
  # Removed file

Medicago/truncatula/annotations/HM004.gnm1.ann1.2XTB/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM010.gnm1.ann1.WV9J/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM022.gnm1.ann1.6C8N/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM023.gnm1.ann1.WZN8/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM034.gnm1.ann1.YR6S/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM050.gnm1.ann1.GWRX/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM056.gnm1.ann1.CHP6/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM058.gnm1.ann1.LXPZ/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM060.gnm1.ann1.H41P/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM095.gnm1.ann1.55W4/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM125.gnm1.ann1.KY5W/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM129.gnm1.ann1.7FTD/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM185.gnm1.ann1.GB3D/transcript2gene
  # Removed file

Medicago/truncatula/annotations/HM324.gnm1.ann1.SQH2/transcript2gene
  # Removed file

Medicago/truncatula/annotations/jemalong_A17.gnm5.ann1_6.L2RX/.iprscan_updated
  # Removed file

Medicago/truncatula/annotations/jemalong_A17.gnm5.ann1_6.L2RX/all.iprscan_raw
  # Removed file

Medicago/truncatula/annotations/jemalong_A17.gnm5.ann1_6.L2RX/error.log
  # Removed file
```

**Comment by sammyjava** [comment]
Thanks!! I think what happened is that I blithely uploaded Medicago up from what I thought was a local NCGR mirror of the DS which actually has millions of locally-generated files in it that don't belong in the DS. After I realized it I guess I didn't clean all the extras out, so thanks for doing that on my forgetful behalf. (Needless to say I ignore that local "mirror" now and have gone back to maintaining my own copy for mine loading and DS back-updating; although the vast majority of that was metadata which is now sweetly updated via GitHub.)

BTW, a nice thing about having metadata in a repo is that git status flags collections that lack a README and therefore the directories weren't added (or even the containing directory in the case of truncatula/diversity):
```
        Medicago/truncatula/diversity/
        Vigna/unguiculata/annotations/Xiabao_II.gnm1.ann1.4JFL/
```
@nathanweeks can you delete v2/foobar.txt? That's a rename I just did of a .nfs orphan of a CHANGES file but I cannot seem to delete it even though it's ug+w. It wasn't recreated so I don't think there's a process holding onto the original file. I forget how to delete this if it's possible for me. (There is no lsof so I don't know how to find an owning process if there is one, but I don't think there is one.)

**Comment by cann0010** [comment]
OK, good.
"a nice thing about having metadata in a repo is that git status flags collections that lack a README and therefore the directories weren't added" - yes, it will be nice to have a more unified, targeted tracking of selected metadata in git. Those of us working in the DS will need some guidance about expectations & best practices for git updates. For example, after the fixes above, I probably should have done the relevant updates (add, rm, commit, push) - but will each of us do this, every time we have a session that impacts metadata files?

**Comment by nathanweeks** [comment]
> @nathanweeks can you delete v2/foobar.txt? That's a rename I just did of a .nfs orphan of a CHANGES file but I cannot seem to delete it even though it's ug+w. It wasn't recreated so I don't think there's a process holding onto the original file. I forget how to delete this if it's possible for me. (There is no lsof so I don't know how to find an owning process if there is one, but I don't think there is one.)

Deleted.  Not sure why you were unable to, but NFS works in mysterious (mostly POSIX, but not quite) ways...

**Comment by adf-ncgr** [comment]
I think the idea is that the Jekyll site will be built from a fresh clone of the repo so if you want changes in these files to be reflected on the site you will have to push them to GitHub. Definitely worth making sure we’re all clear on what the plan is though (e.g. do we require changes to be pulled into the central datastore rather than allowing curation in place? This would presumably be the way to enforce validation prior to publication)

**Comment by sammyjava** [comment]
I have no plan to build the Jekyll site from a clone of the repo. It sucks data directly from the ISU server via HTTPS.

**Comment by sammyjava** [comment]
@cann0010 **absolutely add/commit/push your updates whenever you make a metadata add/change.** That also insures, via the soon-to-come GitHub Actions validation, that your work resulted in valid metadata.

This is, somewhat, the Whole Point. Up to now, the metadata have been a hodgepodge of inconsistency. By putting them into a repo, with a validate script, we can hope that it will remain consistent into the future after I've finished my README fixes.

We're using the GitHub repo for its validation as much as we're using it as a repository, since we cannot rely on LIS humans to run the validate script and do the required fixes. (That I *know*.) But it's also a huge convenience: I edit the metadata locally on my laptop with Emacs, and simply do a commit/push (and then pull on lis) when I'm done with a chunk. It's really nice to not have to work on the lis server or rely on uploading/unpacking tarballs.

**Comment by sammyjava** [comment]
@nathanweeks I got another one when I deleted a file. I really don't get why I cannot delete them. It fails without any message.
```
Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY/.nfs.3b90b548.525c4.4
```
Given that, all we have left is a couple directories lacking READMEs, which will be dealt with, so I'll close this issue.
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY/.nfs.3b90b548.525c4.4
        Medicago/truncatula/diversity/
        Vigna/unguiculata/annotations/Xiabao_II.gnm1.ann1.4JFL/
```

**Comment by nathanweeks** [comment]
> @nathanweeks I got another one when I deleted a file. I really don't get why I cannot delete them. It fails without any message.
> 
> ```
> Medicago/truncatula/annotations/A17_HM341.gnm4.ann2.G3ZY/.nfs.3b90b548.525c4.4
> ```

That's weird. Deleting it from a different (CentOS 8) host worked; possibly an NFS client bug?

**Comment by nathanweeks** [comment]
> > @nathanweeks can you delete v2/foobar.txt? That's a rename I just did of a .nfs orphan of a CHANGES file but I cannot seem to delete it even though it's ug+w. It wasn't recreated so I don't think there's a process holding onto the original file. I forget how to delete this if it's possible for me. (There is no lsof so I don't know how to find an owning process if there is one, but I don't think there is one.)
> 
> Deleted. Not sure why you were unable to, but NFS works in mysterious (mostly POSIX, but not quite) ways...

My bad, I couldn't delete foobar.txt, only turn it into a .nfs orphan---which couldn't be deleted from the jail, which null (bind) mounts an NFS mount from the host. However, the .nfs file could be deleted from the host, suggesting this may be some subtle issue related to null mounting an NFS mount...

**Comment by adf-ncgr** [comment]
> This is, somewhat, the Whole Point. Up to now, the metadata have been a hodgepodge of inconsistency. By putting them into a repo, with a validate script, we can hope that it will remain consistent into the future after I've finished my README fixes.

that's why I thought we would be building off of a fresh clone, to ensure that the files have gone through the vetting process. But it's your call.

**Comment by sammyjava** [comment]
The Jekyll site will represent *exactly* what is in the current DS, as revealed by the DS web interface, which is sourced from the DS on the lis servers. One of my major goals here is to make the DS self-consistent and ALSO exactly equal to what's presented on the Jekyll site. That's hardly a "call" - unless it's a "call" to implement god data and UI management principles.

(I will add that since the mines are loaded intermittently, there is, unfortunately, the possibility of a disconnect, but usually once a collection is stable it doesn't change.)

I have no idea why you got that thought. It didn't come from me.

**Comment by nathanweeks** [comment]
> I have no plan to build the Jekyll site from a clone of the repo. It sucks data directly from the ISU server via HTTPS. I will be checking the ISU DS regularly to see that it is valid, since it is the authoritative DS that is viewed with the browser interface. Ideally, it would be always be updated via git pull, and therefore valid, but I know I cannot count on that.

Perhaps the eventual protocol could be to:
1. Push metadata changes to a separate branch in legumeinfo/datastore-metadata
2. Submit a PR to merge into the main branch (assuming validation checks passed), selecting an appropriate party to review the PR
3. Merge the PR into `main` (possibly done by the reviewer)
4. Author (or reviewer) does a manual "git pull" in the ISU DS (this last step could perhaps be automated)

Then legumeinfo/datastore-metadata might be considered authoritative enough?

**Comment by sammyjava** [comment]
Well, that's the normal way that a repo's main branch is updated. I think a branch PR merge is overkill, though, given that the validation occurs at the commit and will scream at the user (and others) if there is an invalid file. Plus, folks should be able to edit files directly on the LIS server for expediency (and, hopefully, commit their changes). I don't want to insert extra effort into something that is low-level and would likely hinder folks from doing minor updates, which we want them to do.

Running `validate` in a cron task periodically would be a good idea. We have to assume that files will be edited/added directly and not committed. Which is fine when we have a way of finding out reasonably quickly. I'm not concerned about metadata that is invalid for a short time, it's a low price to pay to keep a low barrier to updating.

The main editors will run validation, this is about enabling less active DS contributors to update things (e.g. an article was just published and now has a DOI) without hindrance.

Note that the *Jekyll site IS updated via branch merge* in my current scenario, and the DS scripts will fail if there are broken metadata (just description files at the moment but I expect we'll load data from collection READMEs as well). So there is already a layer of protection against invalid metadata in website updates, no worries there.
