### ISSUE TITLE
Split Glycine/max/diversity/Wm82.gnm2.div.Song_NAM_2021 into two collections

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#73]
I need to split Glycine/max/diversity/Wm82.gnm2.div.Song_NAM_2021 into two collections, since it's two different assays, and we do not support multiple publications, descriptions, etc. per collection.

description: 
  - "The files glyma.Wm82.gnm2.div.Song_NAM_2021.imputed1_5176RILs_29kSNPs* contain imputed genotypes of the 5176 NAM RILs using the 40 NAM parental genotypes obtained from SoySNP50K and SoyNAM6K assays. The imputation was performed by each of the 39 families except for the NAM46 family which has a high percentage of non-parental alleles. The imputed dataset contained the genomics position in Glyma1.01 and Wm82a2v1 assemblies as well as genotypes of 29416 SNPs for 5176 RILs. The common genotype IA3023 alleles were changed to “B”, and the non-IA3023 alleles to “A”.  In addition, the linkage map position of each SNP was inferred based on SNP physical position and the high-density linkage map of Williams 82 x PI479752 consisting of 21,478 SNPs (Song et al. 2016., BMC Genomics 17:33)."
  - "The files glyma.Wm82.gnm2.div.Song_NAM_2021.imputed2_5176RILs_423kSNPs* contain imputed genotypes of the 5176 Nested Association Mapping (NAM) RILs using the 40 NAM parental genotypes obtained from whole genome sequencing, SoySNP50K and SoyNAM6K BeadChip assays. The imputation was performed for each of the 39 families, except for the NAM46 family which has a high percentage of non-parental alleles, using its bi-parental alleles. The imputed dataset contained position in the Wm82a2v1 WGS assembly as well as the genotypes of the  426,937 SNPs for each of 5176 RILs, the alleles identical to  the alleles of the common genotype IA3023 were changed  to “B”, and the non-IA3023 alleles to “A”. In addition, the linkage map position of each SNP was inferred based on SNP physical position and the high-density linkage map of Williams 82 x PI479752 consisting of 21,478 SNPs (Song et al. 2016., BMC Genomics 17:33)."

How about:

Glycine/max/diversity/Wm82.gnm2.div.Song_NAM_2021a/ contains imputed1_5176RILs_29kSNPs
Glycine/max/diversity/Wm82.gnm2.div.Song_NAM_2021b/ contains imputed2_5176RILs_423kSNPs

**Comment by sammyjava** [comment]
@cann0010 just popping this in here for your confirmation, I'll do the work.

**Comment by cann0010** [comment]
Thanks. I agree with the rationale for the split. Thanks for tackling this.

**Comment by sammyjava** [comment]
I did this.
