### ISSUE TITLE
Many collection strains lack an entry in the description_Genus_species.yml

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#76]
The mines get strain identifiers from the collection identifiers, but those strains are often missing from the description YAML, leading to user dissatisfaction: "What's special about FiskebyIII?" (other than having a Swedish name that means _Fishing village III_, making one wonder what happened to Fishing villages I and II). For example:
```
grep identifier /data/v2/Glycine/max/about_this_collection/description_Glycine_max.yml 
  - identifier: Wm82
  - identifier: Zh13
  - identifier: Lee
```
Lacks **FiskebyIII, Hefeng25_IGA1002, Huaxia3_IGA1007, Jinyuan_IGA1006, Wenfeng7_IGA1001, Wm82_IGA1008, Zh35_IGA1004**:
```
$ ls -1 /data/v2/Glycine/max/genomes/
FiskebyIII.gnm1.F177
Hefeng25_IGA1002.gnm1.L69T
Huaxia3_IGA1007.gnm1.RGGN
Jinyuan_IGA1006.gnm1.LXM0
Lee.gnm1.BXNC
Wenfeng7_IGA1001.gnm1.L0QH
Wm82.gnm1.FCtY
Wm82.gnm2.DTC4
Wm82.gnm4.4PTR
Wm82_IGA1008.gnm1.5CQQ
Zh13.gnm1.N6C8
Zh13.gnm2.LV9P
Zh13_IGA1005.gnm1.FRXQ
Zh35_IGA1004.gnm1.DBYJ
```
I can track these down but this sounds like another great task for an Iowa State undergrad or other worker.

**Comment by sammyjava** [comment]
Done. The big update was Jinyuan_IGA1006 -> Jingyuan_IGA1006 to match the name given by the publication that is cited in the README "Eight soybean reference genome resources from varying latitudes and agronomic traits."

I left all the M. truncatula HMnnn entries empty other than adding their identifiers. It'd be nice if we said something about all those lines, but I don't know if there are distinct phenotypes associated with those 21 lines.

Since we have A17 and A17_HM341, they needed two entries in the description file, which are distinguished by the identifier used by the collection, not the plant line itself. Same deal with Wm82 and the Wm82_IGA1008 used in "Eight Shades of Soybean."

**Comment by cann0010** [comment]
After much discussion and some research by Wei regarding lines called "Jinyuan," I have reverted to the name Jinyuan_IGA1006 in all files. The publication uses the form Jingyuan in one place, but GenBank record prjna561626 uses Jinyuan (no "g"). This accession may be in the same lineage as others called Jinuan, e.g. https://npgsweb.ars-grin.gov/gringlobal/accessiondetail?id=1370763. 
The name is consistent with lines named 金 源 大豆 / Jīn yuán dàdòu / Gold source soybean
