### ISSUE TITLE
Marker file needs gzip

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#79]
Spinoff of issue #64: this file should be gzipped (.gff3.gz).
  https://legumeinfo.org/data/v2/Phaseolus/vulgaris/markers/G19833.gnm1.mrk.Parker_BernyMierYTeran_2020/phavu.G19833.gnm1.mrk.Parker_BernyMierYTeran_2020.gff3

**Comment by sammyjava** [comment]
So gzip it. You're a curator, too.

**Comment by svengato** [comment]
I will do it as soon as I can get back on lis-stage or equivalent (did they
move it? my tunnel configuration no longer works).

-Sven-

**Comment by sammyjava** [comment]
I always just ssh to lis and then ssh from there to lis-stage. Two steps.

alias ssh-lis='ssh -p 26 shokin@lis.usda.iastate.edu'

**Comment by svengato** [comment]
The first step still works, but the second no longer accepts my password. I
have a message in to Nathan about it.

**Comment by nathanweeks** [comment]
Following up offline. Also, `bgzip --compress-level -9` should be used to for the 10-15% (depending on file type) data storage & bandwidth savings. Is that something that needs to be implemented in bionorm (@ctcncgr )?

**Comment by svengato** [comment]
Done, using `bgzip --compress-level 9`.
