### ISSUE TITLE
Synteny files do not match up with FASTAs and annotation files

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#8]
I've started modifying my synteny GFF loader for the datastore files and find that the synteny files do not have the same detail on the chromosome names as the FASTAs and annotation files, which prevents merging.

For one, the filename itself is seemingly inconsistent:
```
phavu.G19833.v2.x.aradu.V14167.v1.gff
```
while a genome fasta file, for example, is
```
phavu.G19833.gnm2.fC0g.genome_main.fna
```
What do "v2" and "v1" mean? I realize I can get the genome version from the enclosing directory (`G19833.gnm2.ann1.syn1.DVDW`) but I'm not sure that's wise. And it looks suspiciously like 'v2' in the synteny GFF name corresponds to 'gnm2' in the FASTA and enclosing directory. If not, tell me what it is; if so, please change it to 'gnm2'. :)

So then there's the issue of the chromosome names within the GFFs. Here's what happens when I run my GFF loader and my Synteny loader against phavu:
```
primaryIdentifier
-----------------
 Pv01
 Pv02
 Pv03
 Pv04
 Pv05
 Pv06
 Pv07
 Pv08
 Pv09
 Pv10
 Pv11
 phavu.G19833.gnm1.Chr01
 phavu.G19833.gnm1.Chr02
 phavu.G19833.gnm1.Chr03
 phavu.G19833.gnm1.Chr04
 phavu.G19833.gnm1.Chr05
 phavu.G19833.gnm1.Chr06
 phavu.G19833.gnm1.Chr07
 phavu.G19833.gnm1.Chr08
 phavu.G19833.gnm1.Chr09
 phavu.G19833.gnm1.Chr10
 phavu.G19833.gnm1.Chr11
 phavu.G19833.gnm2.Chr01
 phavu.G19833.gnm2.Chr02
 phavu.G19833.gnm2.Chr03
 phavu.G19833.gnm2.Chr04
 phavu.G19833.gnm2.Chr05
 phavu.G19833.gnm2.Chr06
 phavu.G19833.gnm2.Chr07
 phavu.G19833.gnm2.Chr08
 phavu.G19833.gnm2.Chr09
 phavu.G19833.gnm2.Chr10
 phavu.G19833.gnm2.Chr11
```
So I either have to prepend `phavu.G19833.gnm2` to the chromosomes AND change "Pv" to "Chr" ... which is Bad Practice ... or we need to change the chromosome identifiers in the Synteny files to be at least the same in the least-significant chunk ('Chr01' rather than 'Pv01'). Since the enclosing directory is `G19833.gnm2.ann1.syn1.DVDW` I *can* pull "G19833.gnm2` off of that, but it'd be nice if the GFF had the actual full-yuck chromosome names (in both the source=sequence column and target=match attribute).

**Comment by adf-ncgr** [comment]
yes, I used to have to do quite a bit of tussling to get these files munged (sensu "yuckification") in order to get them to load into chado. I haven't been worrying too much about it since GCV computes macrosynteny on the fly, but that doesn't help you much in your efforts to go "pure datastore". I suspect there will be a fair amount of drift in the naming conventions since I did the aforementioned tussling so why I may still have the "yuckified" files around for some of these, they may have "stale yuck" instead of "fresh yuck". 

In any case, before some hapless curator is forced to deal with your completely legitimate points, let's make sure we all thing there is sufficient utility in storing a static representation of synteny, and of so what we think the best form for it would be (IMHO the gff basically only gives very a very high level summary of what the analysis has done; maybe having the actual gene pairs behind the blocks would be useful, or per-gene pair Ks values in addition to the median values of the blocks). 

my hasty few cents

**Comment by adf-ncgr** [comment]
PS. thanks for getting the ball rolling on this discussion

**Comment by sammyjava** [comment]
Well, it didn't roll for very long before you inserted a precondition. :) In the meantime, I'll just sed the files to make them work. I prefer the existence of data that can be easily loaded and merged over the discussion of nonexistent data to load with nonexistent data loaders in the future.

**Comment by adf-ncgr** [comment]
thanks, sounds like you just signed yourself on as the hapless curator! I'll scuttle off to my future utopia but if you find your self moving from sed to harder tools, please get help. Also, I suspect that Connor's framework for handling gene models gffs might work to some extent with synteny-oriented gffs, but probably there would be some extra bits to encode as far as desired standards. Oh, the utopian bus just pulled up, I've got to catch this one...

**Comment by sammyjava** [comment]
Another inconsistency: adding the annotation version to chromosomes, which do not have annotation versions, in the glyma synteny files:
```
glyma.Wm82.gnm2.ann1.Gm20
```
That should be `glyma.Wm82.gnm2.Gm20`.

**Comment by sammyjava** [comment]
Hrm. Now I'm finding more yucky versions under G19833.gnm2.ann1.syn1.DVDW. I'll back off for now. There is an elf at work.

**Comment by cann0010** [comment]
I am afraid the synteny files are an aspect of the data store that we've never rigorously specified. Many of the files predate the origin of the data store, in fact. I have a few other big things first on my queue, and I am also reluctant to tackle these while Wei is out (she was the generator). She's out through the end of June. Can we set the overhaul as a task for July?

**Comment by sammyjava** [comment]
Gotcha. I'll just fix 'em, it's easy, and upload the results back to LIS. I'll have a copy in case they get stomped on by further analysis.

**Comment by cann0010** [comment]
OK. Much appreciated.

**Comment by adf-ncgr** [comment]
FWIW I just ran across this issue
https://github.com/LegumeFederationDataStore/about_the_data_store/issues/4
which seems relevant to this discussion

**Comment by sammyjava** [comment]
Just ran into this one again, in that some of the synteny directories and/or files have ".ann1." while others do not. Aren't synteny blocks based strictly on the assembly, not the annotation? Isn't it correct to NOT have the ".ann1" etc. in the filename? They're storied in ".syn1.ABCD" files so they're not, in fact, in the annotation directories.
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.araip.K30076.gnm1.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.cajca.ICPL87119.gnm1.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.lotja.MG20.gnm3.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.lupan.Tanjil.gnm1.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.phavu.G19833.gnm1.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.phavu.G19833.gnm2.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.vigan.Gyeongwon.gnm3.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.vigra.VC1973A.gnm6.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.aradu.V14167.gnm1.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.glyma.Wm82.gnm2.gff
./Phaseolus_vulgaris/G19833.gnm1.syn1.DVDW/phavu.G19833.gnm1.x.medtr.A17_HM341.gnm4.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.aradu.V14167.v1.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.araip.K30076.v1.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.cajca.ICPL87119.v1.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.glyma.Wm82.a2.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.lotja.MG-20.v3.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.medtr.A17.HM341.v4.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.phavu.G19833.v1.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.vigan.Gyeongwon.v3.gff
./Phaseolus_vulgaris/G19833.gnm2.ann1.syn1.DVDW/phavu.G19833.v2.x.vigra.VC1973A.v6.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.aradu.V14167.gnm1.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.araip.K30076.gnm1.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.cajca.ICPL87119.gnm1.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.glyma.Wm82.gnm2.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.lotja.MG20.gnm3.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.lupan.Tanjil.gnm1.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.medtr.A17_HM341.gnm4.ann2.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.phavu.G19833.gnm1.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.phavu.G19833.gnm2.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.vigan.Gyeongwon.gnm3.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.gnm1.ann1.x.vigra.VC1973A.gnm6.ann1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.aradu.V14167.v1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.araip.K30076.v1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.cajca.ICPL87119.v1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.glyma.Wm82.a2.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.lotja.MG-20.v3.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.medtr.A17.HM341.v4.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.phavu.G19833.v1.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.vigan.Gyeongwon.v3.gff
./Phaseolus_vulgaris/G19833.gnm1.ann1.syn1.xQ7F/phavu.G19833.v2.x.vigra.VC1973A.v6.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.phavu.G19833.gnm1.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.phavu.G19833.gnm2.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.vigan.Gyeongwon.gnm3.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.vigra.VC1973A.gnm6.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.aradu.V14167.gnm1.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.araip.K30076.gnm1.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.cajca.ICPL87119.gnm1.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.lotja.MG20.gnm3.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.lupan.Tanjil.gnm1.gff
./Glycine_max/Wm82.gnm2.syn1.HXNY/glyma.Wm82.gnm2.x.medtr.A17_HM341.gnm4.ann2.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.aradu.V14167.gnm1.ann1.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.araip.K30076.gnm1.ann1.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.glyma.Wm82.gnm2.ann1.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.lupan.Tanjil.gnm1.ann1.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.medtr.A17_HM341.gnm4.ann2.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.phavu.G19833.gnm1.ann1.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.phavu.G19833.gnm2.ann1.gff
./Arachis_ipaensis/K30076.gnm1.ann1.syn1.S8s4/araip.K30076.gnm1.ann1.x.vigra.VC1973A.gnm6.ann1.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.aradu.V14167.gnm1.ann1.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.araip.K30076.gnm1.ann1.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.glyma.Wm82.gnm2.ann1.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.lupan.Tanjil.gnm1.ann1.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.medtr.A17_HM341.gnm4.ann2.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.phavu.G19833.gnm1.ann1.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.phavu.G19833.gnm2.ann1.gff
./Arachis_duranensis/V14167.gnm1.ann1.syn1.qmkW/aradu.V14167.gnm1.ann1.x.vigra.VC1973A.gnm6.ann1.gff
./Cajanus_cajan/ICPL87119.gnm1.ann1.syn1.Nkx0/cajca.ICPL87119.gnm1.ann1.x.glyma.Wm82.gnm2.ann1.gff
./Cajanus_cajan/ICPL87119.gnm1.ann1.syn1.Nkx0/cajca.ICPL87119.gnm1.ann1.x.lotja.MG20.gnm3.ann1.gff
./Cajanus_cajan/ICPL87119.gnm1.ann1.syn1.Nkx0/cajca.ICPL87119.gnm1.ann1.x.phavu.G19833.gnm1.ann1.gff
./Cajanus_cajan/ICPL87119.gnm1.ann1.syn1.Nkx0/cajca.ICPL87119.gnm1.ann1.x.phavu.G19833.gnm2.ann1.gff
./Cajanus_cajan/ICPL87119.gnm1.ann1.syn1.Nkx0/cajca.ICPL87119.gnm1.ann1.x.vigan.Gyeongwon.gnm3.ann1.gff
./Cajanus_cajan/ICPL87119.gnm1.ann1.syn1.Nkx0/cajca.ICPL87119.gnm1.ann1.x.cajca.ICPL87119.gnm1.ann1.gff
./Cicer_arietinum/CDCFrontier.gnm1.ann1.syn1.7Bqh/cicar.CDCFrontier.gnm1.ann1.x.cicar.CDCFrontier.gnm1.ann1.gff
./Cicer_arietinum/CDCFrontier.gnm1.ann1.syn1.7Bqh/cicar.CDCFrontier.gnm1.ann1.x.cicar.ICC4958.gnm2.ann1.gff
./Cicer_arietinum/CDCFrontier.gnm1.ann1.syn1.7Bqh/cicar.CDCFrontier.gnm1.ann1.x.lotja.MG20.gnm3.ann1.gff
./Cicer_arietinum/CDCFrontier.gnm1.ann1.syn1.7Bqh/cicar.CDCFrontier.gnm1.ann1.x.medtr.A17_HM341.gnm4.ann2.gff
./Cicer_arietinum/CDCFrontier.gnm1.ann1.syn1.7Bqh/cicar.CDCFrontier.gnm1.ann1.x.tripr.MilvusB.gnm2.ann1.gff
./Cicer_arietinum/ICC4958.gnm2.ann1.syn1.PdvJ/cicar.ICC4958.gnm2.ann1.x.cicar.CDCFrontier.gnm1.ann1.gff
./Cicer_arietinum/ICC4958.gnm2.ann1.syn1.PdvJ/cicar.ICC4958.gnm2.ann1.x.cicar.ICC4958.gnm2.ann1.gff
./Cicer_arietinum/ICC4958.gnm2.ann1.syn1.PdvJ/cicar.ICC4958.gnm2.ann1.x.lotja.MG20.gnm3.ann1.gff
./Cicer_arietinum/ICC4958.gnm2.ann1.syn1.PdvJ/cicar.ICC4958.gnm2.ann1.x.medtr.A17_HM341.gnm4.ann2.gff
./Cicer_arietinum/ICC4958.gnm2.ann1.syn1.PdvJ/cicar.ICC4958.gnm2.ann1.x.tripr.MilvusB.gnm2.ann1.gff

**Comment by adf-ncgr** [comment]
I believe that the method used for creating these synteny files actually works by focusing on matching CDS sequences (giving the Ks values) and looking at the collinearity of the genes from which they were derived. I'm pretty sure that this was the reason for a decision being made to hang them off the "ann". That they are not consistent in this regard does not surprise me, however.

**Comment by sammyjava** [comment]
Ah ok, I thought was "blast this genome against this other one" :)

**Comment by cann0010** [comment]
@adf-ncgr - I agree on both counts (synteny is calculated based on comparisons among the protein & CDS files) - and the inconsistency is unsurprising. This is a corner of the DS where we have not nailed down or enforced the requirements.

**Comment by sammyjava** [comment]
In any case, make a Diktat and I'll implement it in my local copy of these files.

**Comment by sammyjava** [comment]
Closing this, I'll just rename files as they should be named when I come across incorrectly-named files, if there are any left.
