### ISSUE TITLE
medtr.A17.gnm5.ann1_6 has IDs that are identical for genes and mRNAs

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#84]
They used to be differentiated by the genes having a "gene:" and the mRNAs having "mRNA:" as can be seen in the original representations at https://medicago.toulouse.inra.fr/MtrunA17r5.0-ANR/ e.g.
gene:MtrunA17Chr8g0379571 mRNA:MtrunA17Chr8g0379571

not sure who changed them or why, but I ran into this when doing the new GCV loading due to the gfa file having the older-style IDs. Since GCV itself doesn't care about the mRNA, I just altered the gfa to match what's now in the gff (ie no "gene:") but I suspect that having gene ID = mRNA ID is going to cause problems downstream as for example in JBrowse (though for some reason this is being called a NonError?):
<img width="660" alt="image" src="https://user-images.githubusercontent.com/2009605/156939064-f0544197-f483-41cb-84e7-e7303e49afb1.png">

**Comment by sammyjava** [comment]
This loaded today.
