### ISSUE TITLE
all the following taxa falsely assert that they have no resources in datastore, presumably due to missing yml

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#89]
[Bauhinia](https://jekyll-stage.legumeinfo.org/taxa/bauhinia) (Orchid tree)
[Cercis](https://jekyll-stage.legumeinfo.org/taxa/cercis) (Redbud tree)
[Chamaecrista](https://jekyll-stage.legumeinfo.org/taxa/chamaecrista) (Partridge pea)
[Faidherbia](https://jekyll-stage.legumeinfo.org/taxa/faidherbia) (Apple-ring acacia)
[Zenia](https://jekyll-stage.legumeinfo.org/taxa/zenia) (Southeast Asian tree)

I'm sure this is a temporary oversight in the datastore, but wondering if it would it be better not to let them appear at all as taxa if they don't provide the full needful?

**Comment by sammyjava** [comment]
Indeed, those genera lack genus and genus_species description files. I say let's yank them from taxon_list.yml until they have description files. One purpose of listing genera in taxon_list.yml, and species in the description files, is to determine which things do and do not appear on the website.

Say the word and I'll take care of it. We can assign someone to build those description files. Bauhinia and Zenia don't have genomes or annotations, anyway, just as-yet-unspecified /transcriptomes/ collections.

**Comment by sammyjava** [comment]
Update: I'm building the description files for Cercis, Chamaecrista, and Faidherbia, since those contain genomes and annotation. I'll yank Bauhinia and Zenia since we don't load /transcriptomes/ collection READMEs onto the website.

**Comment by cann0010** [comment]
Thank you. I agree about handling only the genera for which we have assemblies.
We'll be getting much-improved assemblies for Cercis and Chamaecrista soon (have them now, actually, but are waiting on annotations).

**Comment by adf-ncgr** [comment]
tangentially related to improved assemblies; I see @weihuang12 just promoted the new Trifolium subterraneum and improved Cajanus cajan assemblies/annotations. We will try to get them propagated around to the relevant pieces of the new system.

**Comment by sammyjava** [comment]
I'm going to close this since there's nothing left to do and create an issue-for-the-future to remind us to create description files when we've got assemblies and annotations up for Bauhinia and Zenia.
