### ISSUE TITLE
We need a licence (yes, British spelling) to enter into the mines for the DS

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#9]
So a FAIRy thing that's been implemented in InterMine is that you should enter a license associated with a DataSource, which is meant to be a URL. A classic example is the **Creative Commons Attribution-NonCommercial 3.0 Unported License** which I have on the footer of pure-gas.org:

https://creativecommons.org/licenses/by-nc/3.0/

So what's the license associated with the LIS Datastore files???

**Comment by cann0010** [comment]
We used GPU v3.0.
I don't know whether that's the most appropriate, but it's what we have now.
https://github.com/LegumeFederationDataStore/about_the_data_store

**Comment by sammyjava** [comment]
OK, I didn't want to conflate the LegFed datastore, hosted at CyVerse, with the LIS datastore, hosted at ISU. I'll go with GPUv3.0 and throw it on this repo as well.

**Comment by adf-ncgr** [comment]
I may be confused (likely) but I think that LICENSE file is just the one that was auto-created (more or less) when the github repository was initialized. It probably isn't all that appropriate for the data (which doesn't actually live in github either, adding further confusion to the subject of what that license would actually govern...)

**Comment by adf-ncgr** [comment]
PS. is it actually possible not to conflate these things? I think the only reason this repository exists is to track issues pertaining to weirdities in the legumeinfo datastore (which will become weirdities in the legfed datastore, if left unchecked...)

good attempt at unconflation, though

**Comment by sammyjava** [comment]
I just consider the Legume Federation to be a dead parrot these days. It'd be pushing up daisies if you hadn't nailed it to the perch! (And I think GPUv3 is perfectly fine, I just want to impose SOME real license on my data sources so Yo doesn't stop sending me gifts.)

**Comment by sammyjava** [comment]
OH and AFAIK Github never auto-creates a license, you have to actively add one, even if it is suggested by Github. Some Legfedder added or accepted GPUv3 when they created that other repo. The one on the perch.

**Comment by adf-ncgr** [comment]
it's just pining for the NSFjords... and yes you're right a legfedder must have accepted that license (typically referred to as GPLv3 not GPUv3, I believe; either one is an acceptable anagram for Notlob, however)

anyway, I will stop beating the dead Norwegian here

**Comment by nathanweeks** [comment]
I'm far from competent in this subject, but it seems a software license like GPLv3 isn't a good fit for a data set? Open Data Commons [lists several licenses for data sets](https://help.data.world/hc/en-us/articles/115006114287-Common-license-types-for-datasets), and data.world (which seems to be a "startup" that describes itself as a "cloud-native data catalog") [lists a few others](https://help.data.world/hc/en-us/articles/115006114287-Common-license-types-for-datasets).

Regarding a software license for things like scripts in https://github.com/LegumeFederationDataStore/ : I don't think the primary contributor (@cann0010) can assign a license other than Public Domain to his original work?

**Comment by sammyjava** [comment]
Hrm, here's an ODC license that seems appropriate:

https://opendatacommons.org/licenses/by/

And here's the similar CC license:

https://creativecommons.org/licenses/by/4.0/

Both seem fine to me, I lean toward CC but if there's a reason to prefer ODC I'm fine.

**Comment by adf-ncgr** [comment]
OK, I have no preference but let's spend <=3 minutes making a final decision in today's mtg according to whatever additional restrictions our collaborators may be subject to. I'll add an agenda item.

**Comment by sammyjava** [comment]
Closing this, the datasets in the mines all use "ODC Public Domain Dedication and Licence (PDDL)" 

https://opendatacommons.org/licenses/pddl/1-0/
