### ISSUE TITLE
Missing common bean QTL README.yml

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#93]
https://data.legumeinfo.org/Phaseolus/vulgaris/genetic/ICABunsi_x_SXB.qtl.Parker_BernyMierYTeran_2020/
has no README.yml file. I am pretty sure it used to, otherwise I could not have created the common bean QTL dataset for ZZBrowse.

Could it be the one in this directory? For now, I have copied it to the above directory.
https://data.legumeinfo.org/Phaseolus/vulgaris/genetic/ICABunsi_x_SXB405.gen.Parker_BernyMierYTeran_2020/

**Comment by svengato** [comment]
The only difference is the publication title. I will check the README.yml to make sure it is in the latest format, as it may be getting the title from the wrong field.

**Comment by svengato** [comment]
It seems consistent, the relevant field is 'synopsis'.

**Comment by cann0010** [comment]
The two READMEs are identical. I think the files in ICABunsi_x_SXB.qtl.Parker_BernyMierYTeran_2020 should be moved to ICABunsi_x_SXB405.gen.Parker_BernyMierYTeran_2020 (this data set is of type "gen" rather than "qtl"), and the "qtl" directory then be deleted.

However, there is a bigger issue: all of the other "gen" sets in Phaseolus/vulgaris/genetic are lacking all data files. I see they were all updated on Feb 28. Maybe a data transfer glitch? @shokin

**Comment by sammyjava** [comment]
Yeah, I built those locally but I guess didn't upload them to LIS. Just did. And yes, the .qtl. collection was deprecated, and the .gen. collections all contain data. I deleted that .qtl. collection.

NOTE: I'll be merging/moving the lg.tsv and mrk.tsv files to /maps/ collections in the next BeanMine build. glyma reflects that change as of this morning. The READMEs under /genetic/ will then contain a genetic_map attribute pointing to the collection under /maps/.
```
BAT93_x_JALOEEP558.gen.Blair_Cortés_2018/phavu.BAT93_x_JALOEEP558.gen.Blair_Cortés_2018.mrk.tsv.gz
BAT93_x_JALOEEP558.gen.Freyre_Skroch_1998/phavu.mixed.map.BAT93_x_JALOEEP558_b.mrk.tsv.gz
BAT93_x_JALOEEP558.gen.McConnell_Mamidi_2010/phavu.mixed.map.PvMcCleanNDSU2007.mrk.tsv.gz
Cerinza_x_G24404.gen.Blair_Iriarte_2006/phavu.mixed.map.Cerinza_x_G24404_a.mrk.tsv.gz
DOR364_x_BAT477.gen.Blair_Galeano_2012/phavu.mixed.map.DOR364_x_BAT477_a.mrk.tsv.gz
mixed.gen.Blair_Cortés_2018/phavu.mixed.gen.Blair_Cortés_2018.mrk.tsv.gz
mixed.gen.Galeano_Fernandez_2011/phavu.mixed.map.PvConsensus_GaleanoFernandez2011_a.mrk.tsv.gz
Stampede_x_RedHawk.gen.Song_Jia_2015/phavu.mixed.map.Stampede_x_RedHawk_F2_a.mrk.tsv.gz
[shokin@lis-stage ~/v2/Phaseolus/vulgaris/genetic]$ ls */*.lg.tsv.gz
BAT93_x_JALOEEP558.gen.Blair_Cortés_2018/phavu.BAT93_x_JALOEEP558.gen.Blair_Cortés_2018.lg.tsv.gz
BAT93_x_JALOEEP558.gen.Caldas_Blair_2009/phavu.mixed.map.BAT93_x_JALOEEP558_a.lg.tsv.gz
BAT93_x_JALOEEP558.gen.Freyre_Skroch_1998/phavu.mixed.map.BAT93_x_JALOEEP558_b.lg.tsv.gz
BAT93_x_JALOEEP558.gen.McConnell_Mamidi_2010/phavu.mixed.map.PvMcCleanNDSU2007.lg.tsv.gz
Cerinza_x_G24404.gen.Blair_Iriarte_2006/phavu.mixed.map.Cerinza_x_G24404_a.lg.tsv.gz
DOR364_x_BAT477.gen.Blair_Galeano_2012/phavu.mixed.map.DOR364_x_BAT477_a.lg.tsv.gz
G2333_x_G19839.gen.Checa_Blair_2008/phavu.mixed.map.G2333_x_G19839_a.lg.tsv.gz
mixed.gen.Blair_Cortés_2018/phavu.mixed.gen.Blair_Cortés_2018.lg.tsv.gz
mixed.gen.Galeano_Fernandez_2011/phavu.mixed.map.PvConsensus_GaleanoFernandez2011_a.lg.tsv.gz
Stampede_x_RedHawk.gen.Song_Jia_2015/phavu.mixed.map.Stampede_x_RedHawk_F2_a.lg.tsv.gz
Xana_x_Cornell49242.gen.Gaitán-Solís_Duque_2002/phavu.mixed.map.Xana_x_Cornell49242_a.lg.tsv.gz
```

**Comment by sammyjava** [comment]
What the hell. I have no idea why phavu files have gone missing! I'll get those back in place by hook or by crook. I think they're in chado, otherwise we've got some sleuthing to do. I don't have them locally. It could be all the essential data exists, i.e. there are only QTL-marker associations but no QTL spans on linkage groups, in which case the QTL file simply lists QTL IDs and trait names. Or, the other way, there are only QTL spans on linkage groups but no QTL-marker associations in which case there is no qtlmrk.tsv file. But I'll nail it down for those collections.

OFF TOPIC: As for that soybean collection, it was deleted by me: https://github.com/legumeinfo/datastore-metadata/commit/a030869ce8d516f483dae071eae5ae5f75f06408

The reason being that it did not successfully dump from the soybase mysql database using my new routine that dumped out 288 QTL studies that have findable, accessible publications. Which I have to have to load a collection. But I'm planning to grab another 70-odd that didn't have automatically findable publications, and it will reappear in that case, it's in the database. But consider the current state of collections to be the official current state of collections, with some more to come. Soybean is still a work in progress.

**But let's keep THIS issue about the missing phavu data, OK?** Let's try to keep each issue in GitHub about a specific thing, and not expand it to other issues in the conversation.

**Comment by sammyjava** [comment]
OH, another thing: those file names under Phaseolus/vulgaris/genetic collections are totally fouled up. 

**DO NOT USE Phaseolus/vulgaris/genetic collections until I've got them all up to current spec!**

**Comment by sammyjava** [comment]
And another point: some of these are genetic maps, not QTL experiments. For example:
```
BAT93_x_JALOEEP558.gen.Blair_Cortés_2018
├── phavu.BAT93_x_JALOEEP558.gen.Blair_Cortés_2018.lg.tsv
├── phavu.BAT93_x_JALOEEP558.gen.Blair_Cortés_2018.mrk.tsv
└── README.BAT93_x_JALOEEP558.gen.Blair_Cortés_2018.yml
```
is actually the BAT93_x_JALOEEP558_c genetic map. I don't think there is a QTL study on that, but I'll double-check along with all the others. That will move into the new /maps/ directory. So again, hold on, I have work to do on phavu genetics.

**Comment by cann0010** [comment]
Doing some sleuthing via the .zfs snapshots:
cd /usr/local/www/data/.zfs/snapshot
ls -l auto-2022*/v2/Phaseolus/vulgaris/genetic
New directories appeared on Feb 28, but these were empty. Then, looks like you copied up some files into the directories yesterday, Sam.
(Not very helpful, I know - but sometimes, .zfs/snapshot is a lifesaver. Not in this case, unfortunately.)

**Comment by sammyjava** [comment]
Yeah, I think there actually isn't a loss of data; .gen. collections don't' need to have qtl.tsv and/or qtlmrk.tsv files. But I'm gonna look back at those publications and I need to get the collections in shape, anyway, moving the maps to /maps/, etc.

**Comment by sammyjava** [comment]
OK, yeah, looking at my old file formats I've got all this stuff so this is an easy rebuild, which I think will mainly be moving the maps to /maps/. Here's the old stuff. 
```
These are now README files:
./mixed.map.7PMp/phavu.mixed.map.7PMp.PvConsensus_GaleanoFernandez2011_a.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.DOR364_x_BAT477_a.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.Cerinza_x_G24404_a.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.BAT93_x_JALOEEP558_c.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.Stampede_x_RedHawk_F2_a.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.BAT93_x_JALOEEP558_b.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.PvMcCleanNDSU2007.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.PvCookUCDavis2009.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.BAT93_x_JALOEEP558_a.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.G2333_x_G19839_a.expt.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.Xana_x_Cornell49242_a.expt.tsv
./mixed.qtl.7SDM/phavu.mixed.qtl.7SDM.31486530.expt.tsv = ICABunsi_x_SXB405_a map

qtl.tsv files haven't changed:
./mixed.map.7PMp/phavu.mixed.map.7PMp.BAT93_x_JALOEEP558_a.qtl.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.Xana_x_Cornell49242_a.qtl.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.G2333_x_G19839_a.qtl.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.Cerinza_x_G24404_a.qtl.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.DOR364_x_BAT477_a.qtl.tsv

mrk.tsv files haven't changed:
./mixed.map.7PMp/phavu.mixed.map.7PMp.BAT93_x_JALOEEP558_c.mrk.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.Cerinza_x_G24404_a.mrk.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.PvCookUCDavis2009.mrk.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.DOR364_x_BAT477_a.mrk.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.Stampede_x_RedHawk_F2_a.mrk.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.BAT93_x_JALOEEP558_b.mrk.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.PvMcCleanNDSU2007.mrk.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.PvConsensus_GaleanoFernandez2011_a.mrk.tsv
./mixed.qtl.7SDM/phavu.mixed.qtl.7SDM.31486530.mrk.tsv = ICABunsi_x_SXB405_a map

These are now trait.tsv files:
./mixed.gwas.5HCM/phavu.mixed.gwas.5HCM.31428109.phen.tsv
./mixed.gwas.5HCM/phavu.mixed.gwas.5HCM.31486530.phen.tsv
./mixed.map.7PMp/phavu.mixed.map.7PMp.ALL.phen.tsv
./mixed.qtl.7SDM/phavu.mixed.qtl.7SDM.31486530.phen.tsv
```
There is actually only one file that would be a current qtlmrk.tsv file, the single Pod dehiscence-1 QTL with two flanking markers ss715639553 and ss715639323 from Parker, Berny Mier y Teran et al., 2020a.

But I'll double-check the publications in case there's more to be found, it's not a lot of collections.

**Comment by cann0010** [comment]
Good deal.
I'll also be uploading a new GWAS collection that Scott has curated (mixed.gwas.Tigist_Melis_2019; DOI 10.2135/cropsci2018.09.0559) ... but probably not until Monday or Tuesday, after I finish some ARS budgeting.

**Comment by svengato** [comment]
Great - I will hold off on updating ZZBrowse common bean datasets until these are resolved.

(Also an acknowledgment that I have been conflating ZZBrowse issues with datastore issues. Now I get it, and opened a separate soybean issue, #94.)

**Comment by sammyjava** [comment]
OK I have these sorted out, hopefully. lg and mrk files have moved to /maps/. READMEs are updated throughout.
```
[shokin@lis-stage ~/v2/Phaseolus/vulgaris]$ ls -1 genetic
BAT93_x_JALOEEP558.gen.Caldas_Blair_2009
Cerinza_x_G24404.gen.Blair_Iriarte_2006
DOR364_x_BAT477.gen.Blair_Galeano_2012
G2333_x_G19839.gen.Checa_Blair_2008
ICABunsi_x_SXB405.gen.Parker_BernyMierYTeran_2020
mixed.gwas.DiVittori_Bitocchi_2021
mixed.gwas.Jain_Poromarto_2019
mixed.gwas.Myers_Wallace_2019
mixed.gwas.Oladzad_Porch_2019
mixed.gwas.Parker_BernyMierYTeran_2020
mixed.gwas.Paulino_Almeida_2021
mixed.gwas.Raggi_Caproni_2019
mixed.gwas.Shi_Gepts_2021
mixed.gwas.Wu_Wang_2020
mixed.gwas.Zitnick-Anderson_Oladzad_2020
Xana_x_Cornell49242.gen.Gaitán-Solís_Duque_2002
```
[shokin@lis-stage ~/v2/Phaseolus/vulgaris]$ ls -1 maps
BAT93_x_JALOEEP558.map.Blair_Cortés_2018_c
BAT93_x_JALOEEP558.map.Blair_Cortés_2018_d
BAT93_x_JALOEEP558.map.Caldas_Blair_2009
BAT93_x_JALOEEP558.map.Freyre_Skroch_1998
Cerinza_x_G24404.map.Blair_Iriarte_2006
DOR364_x_BAT477.map.Blair_Galeano_2012
G2333_x_G19839.map.Checa_Blair_2008
mixed.map.Galeano_Fernandez_2011
mixed.map.PvMcCleanNDSU2007
Stampede_x_RedHawk.map.Song_Jia_2015
Xana_x_Cornell49242.map.Gaitán-Solís_Duque_2002
```

**Comment by sammyjava** [comment]
Oh. mixed.map.PvMcCleanNDSU2007 lacks a README because we're trying to track down the relevant publication. @cann0010 emailed him. The lg and mrk files are fine, though.
