### ISSUE TITLE
Missing qtlmrk data in 4 of 321 glyma .gen. collections

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#97]
These four soybean qtlmrk files have no data (markers), only a header. Is that correct?

Chamame_x_Laco-1.gen.Juwattanasomran_Somta_2012
Essex_x_Williams.gen.Hyten_Pantalone_2004
Essex_x_Williams.gen.Hyten_Pantalone_2004a
PI561356_x_LD02-4485.gen.Kim_Unfried_2012

**Comment by sammyjava** [comment]
Chamame_x_Laco-1.gen.Juwattanasomran_Somta_2012: just a QTL on LG, no markers; deleted qtlmrk file
Essex_x_Williams.gen.Hyten_Pantalone_2004: duplicate with 2004a, deleted collection
Essex_x_Williams.gen.Hyten_Pantalone_2004a: just QTLs on LGs, no markers; deleted qtlmrk file
PI561356_x_LD02-4485.gen.Kim_Unfried_2012:  just a solo QTL on LG, no markers; deleted qtlmrk file

This came from my little script to add headers, it created those files when they didn't exist. I forgot to add them to the soybase mysql file dumper.

**Comment by sammyjava** [comment]
BTW I found two more duplicate non-a-suffix collections resulting from my addition of new collections yesterday, deleted:

IA2008_x_PI468916.gen.Wang_Graef_2004
Taekwangkong_x_SS2-2.gen.Sun_Kim_2013
