### ISSUE TITLE
R108_HM340 GFF has multiple-parent records

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#99]
Assigning to you, as I'm quite tired of wrangling Datastore files at this point.

**Comment by sammyjava** [comment]
Caused by: java.lang.RuntimeException: Parent medtr.R108_HM340.gnm1.ann1.BZG31_000s000470.1,medtr.R108_HM340.gnm1.ann1.BZG31_000s000470.2 not loaded before child medtr.R108_HM340.gnm1.ann1.BZG31_000s000470:exon:6. Is the GFF sorted?

**Comment by sammyjava** [comment]
Oh, that has the comma-separated parents. I can't load those, the mine data model does not allow children to have multiple parents. Byzantine. I think we hit this before.

**Comment by adf-ncgr** [comment]
luckily, that's the one that is superceded by R108.gnmHiC_1 so let's skip it. Having multiple parents does seem to be a source of many issues (Oedipal complexes for starters). But if the same issue affects the others I'll try to sort it out.
